<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Expediente Judicial Electrnico</name>
   <tag></tag>
   <elementGuidId>46c1e80a-5edd-46ba-b15f-a117a97127c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.header--titulo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='header--titulo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd8f4a51-79f0-42f7-9405-52579d9841cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header--titulo</value>
      <webElementGuid>856295d2-8877-47eb-9fc4-3528c1e0e8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Expediente Judicial Electrónico</value>
      <webElementGuid>3284d13d-c8f6-442b-af8e-8304a722fb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nav[@class=&quot;navbar navbar-expand-lg header fondo-color-bordo&quot;]/a[@class=&quot;navbar-brand&quot;]/span[@class=&quot;header--titulo&quot;]</value>
      <webElementGuid>a40712b7-6816-46a4-a604-40e4cbadbb2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='menu'])[1]/preceding::span[1]</value>
      <webElementGuid>f3eb1422-0a28-4d04-b45e-edcc7dff1497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número, Año y/o Título'])[1]/preceding::span[2]</value>
      <webElementGuid>967818a2-864c-4ac2-a839-31938968500e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Expediente Judicial Electrónico']/parent::*</value>
      <webElementGuid>64aa5d2c-d78c-4b8f-882c-017c821ae47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>b8c09119-7b2e-4e6b-8ba9-215f14994011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Expediente Judicial Electrónico' or . = 'Expediente Judicial Electrónico')]</value>
      <webElementGuid>0d93d122-f706-4a1d-ae5f-09b24a8bbc20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
