<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_attach_file1</name>
   <tag></tag>
   <elementGuidId>0a9cdf92-ad6c-40f5-abf1-6787e722dfe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='al-verAdjunto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#al-verAdjunto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c710f18-943b-4e0d-8af7-995adb95d0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secContenedor__botones--morfologia botones__abrir-ventana ml-2</value>
      <webElementGuid>40b15c83-401f-4f83-b939-53f48324c2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-verAdjunto</value>
      <webElementGuid>cfb19715-7bea-4958-9cf5-4437ed569a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver Adjuntos</value>
      <webElementGuid>dd60a72e-00f3-43d1-baec-174a9934089f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>attach_file1</value>
      <webElementGuid>99a545a8-dd32-4262-90b4-023d9b166442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-verAdjunto&quot;)</value>
      <webElementGuid>369e4431-5b08-4e7c-a70f-9946d728fe31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='al-verAdjunto']</value>
      <webElementGuid>41f3c98c-6dba-47e3-b7ec-19601d9f16c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create'])[1]/following::a[1]</value>
      <webElementGuid>1dd89b6b-1e06-4d1e-991e-45647309cb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BORRADOR'])[1]/preceding::a[1]</value>
      <webElementGuid>eaf5dc1e-b2ae-4bc3-9448-3d6749587477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>a58e711c-aac5-48b3-8f0c-79092055bf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'al-verAdjunto' and @title = 'Ver Adjuntos' and (text() = 'attach_file1' or . = 'attach_file1')]</value>
      <webElementGuid>6cae1f55-35d8-452d-8a3f-1718e7a0429f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
