<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Con token</name>
   <tag></tag>
   <elementGuidId>d58936c3-cc1a-4ded-a79c-2ff044d8cf73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='al-firmarToken']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#al-firmarToken</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab0d07b1-9fae-446b-baf4-2975c11cbe70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item </value>
      <webElementGuid>16947727-e459-4edf-b08f-54a3886c0fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-firmarToken</value>
      <webElementGuid>a42fb64c-e836-48a0-b58b-ea781859968c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Con token</value>
      <webElementGuid>2b53674e-ce4e-4140-84b1-a63f9e72db18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Con token </value>
      <webElementGuid>a69f3517-2528-476f-a461-d3a02c185658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-dropdown-menu&quot;)/li[@class=&quot;dropwon-item-size ng-star-inserted&quot;]/a[@id=&quot;al-firmarToken&quot;]</value>
      <webElementGuid>7eb76200-2368-46a7-9ac9-67cda6f5119f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='al-firmarToken']</value>
      <webElementGuid>42e79b87-5a6f-46ac-9b98-ebb44ec01899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='al-dropdown-menu']/li/a</value>
      <webElementGuid>7001d2de-4dbe-48a3-933a-adb3d83a49f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Con token')]</value>
      <webElementGuid>7f2b5e15-a5b9-488b-b7d0-f8693e4bff88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar'])[1]/following::a[1]</value>
      <webElementGuid>50a5b09c-eb2b-4167-987f-7cb674d94c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilidad'])[1]/following::a[1]</value>
      <webElementGuid>c0311240-ed6d-4e28-a0b2-5c6cf96b1387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sin token'])[1]/preceding::a[1]</value>
      <webElementGuid>0b6a10d8-a1c5-47db-9d3e-6646c6300865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Con token']/parent::*</value>
      <webElementGuid>5197183a-30bf-4a33-8934-e2b5240bc83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>711d2c36-693d-481f-afd4-dd18acbcc2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'al-firmarToken' and @title = 'Con token' and (text() = ' Con token ' or . = ' Con token ')]</value>
      <webElementGuid>d9de10fd-7493-4d4b-936b-f4bf2ae7edaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
