<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Con token</name>
   <tag></tag>
   <elementGuidId>d58936c3-cc1a-4ded-a79c-2ff044d8cf73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='al-firmarToken']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#al-firmarToken</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6662b966-d675-405a-963f-72c3edb1ff1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item </value>
      <webElementGuid>a99a6316-8e46-4358-891f-6737398d2f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-firmarToken</value>
      <webElementGuid>643d940b-6e02-447a-bd0b-0932aedf5137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Con token</value>
      <webElementGuid>5a502fc5-622c-4647-b550-0dc5721dcaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Con token </value>
      <webElementGuid>14b77b8a-cf9f-43dd-ae3d-c6618acdb7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-dropdown-menu&quot;)/li[@class=&quot;dropwon-item-size ng-star-inserted&quot;]/a[@id=&quot;al-firmarToken&quot;]</value>
      <webElementGuid>99480bb5-c076-42ff-931f-ca50f16c4751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='al-firmarToken']</value>
      <webElementGuid>c7c7e5ee-fbde-424f-ba27-0f73c2f07879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='al-dropdown-menu']/li/a</value>
      <webElementGuid>d2554929-1663-4eb4-a6d8-e02b43e904d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Con token')]</value>
      <webElementGuid>2e7a8d50-9e12-44b4-ad0f-33758cbfd768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar'])[1]/following::a[1]</value>
      <webElementGuid>5d786215-41fa-4c0e-85af-a905490ffefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilidad'])[1]/following::a[1]</value>
      <webElementGuid>5f1342f2-afb7-43e1-a6c4-e29ebabe0bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sin token'])[1]/preceding::a[1]</value>
      <webElementGuid>521363b8-5483-43ad-bae6-00ea9f5cf821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Con token']/parent::*</value>
      <webElementGuid>69f9b5c3-ced7-49d8-9b33-7463d9eafad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>d24ae4b6-534e-456a-a206-bfc0c6b100dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'al-firmarToken' and @title = 'Con token' and (text() = ' Con token ' or . = ' Con token ')]</value>
      <webElementGuid>eee0425c-af3a-45ea-9661-b88d46101b86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
