<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PS103</name>
   <tag></tag>
   <elementGuidId>cbc591be-f65d-41c7-b012-1cf39e35bcc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'PS103')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mab-seleccionarModelo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7059c257-bb92-4533-9842-0859a9f45e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>001c6926-59c6-427b-bc6d-e3f29fefc7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mab-seleccionarModelo</value>
      <webElementGuid>f8df960a-af87-4814-ae6a-7c68ce1095ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>1810842a-0489-4119-924b-84dd32cbc7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PS103</value>
      <webElementGuid>c9b80fd6-00af-4ee5-8701-521e7ccd104a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mab-seleccionarModelo&quot;)</value>
      <webElementGuid>f251888f-87b3-4cda-8f3f-730e126ef01f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mab-seleccionarModelo']</value>
      <webElementGuid>fdd4bf95-302b-45bd-b92f-44163f2dc3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-cell[@id='mab-codigo']/a</value>
      <webElementGuid>a49cae1f-1517-4aad-add4-a61dfa585037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PS103')]</value>
      <webElementGuid>7166e929-01d3-49cb-b121-a63d6c132666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vista Previa'])[1]/following::a[1]</value>
      <webElementGuid>4dc5b290-a8cb-4145-b862-b1a8e4ff9584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[1]/following::a[1]</value>
      <webElementGuid>be8255d4-61ae-43a6-bd16-16385343478b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDEN - ORDEN DE ALLANAMIENTO'])[1]/preceding::a[1]</value>
      <webElementGuid>8bdf8c38-9b0f-4d63-ab34-7a8bcf817fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove_red_eye'])[1]/preceding::a[1]</value>
      <webElementGuid>391d2ba3-c31a-4bc9-9c94-c4e920f8540b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PS103']/parent::*</value>
      <webElementGuid>7f93e243-56dc-4bf0-9fd9-6e41fd4a5308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>3ac8310a-a40f-40dd-badc-b8a3d5179539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell/a</value>
      <webElementGuid>cd69c87a-1854-4483-8ae5-17129ff14b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'mab-seleccionarModelo' and (text() = 'PS103' or . = 'PS103')]</value>
      <webElementGuid>a561c1c2-79ad-4175-8102-5188af8c1fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
