<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PS103</name>
   <tag></tag>
   <elementGuidId>cbc591be-f65d-41c7-b012-1cf39e35bcc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mab-seleccionarModelo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'PS103')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc7e0a0d-a5d9-40b6-8aa7-8d1719b4ea42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>57175448-ee12-4a39-8731-a84e00ce610b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mab-seleccionarModelo</value>
      <webElementGuid>ace11b3a-84c4-44e5-b95b-f38bf3b7b0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>cabc6c93-247c-4dab-965f-fcd5fa66f951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PS103</value>
      <webElementGuid>3dd080fb-e832-481a-b6e9-bb93219bd59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mab-seleccionarModelo&quot;)</value>
      <webElementGuid>8b1d8ee2-5e34-4fbb-8924-e1d2298bf347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mab-seleccionarModelo']</value>
      <webElementGuid>8bafbf5c-4d0d-45a8-bc6d-3c898e63840d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-cell[@id='mab-codigo']/a</value>
      <webElementGuid>c33e4c31-88ce-4b32-b158-2ab77710eb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PS103')]</value>
      <webElementGuid>927eba14-f496-47f0-b2b6-215bafe3348d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vista Previa'])[1]/following::a[1]</value>
      <webElementGuid>c36dd9ed-7509-4b18-b133-7b64b21bf47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[1]/following::a[1]</value>
      <webElementGuid>0052cdff-a8cc-4d9e-afa0-1ac570c7a2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDEN - ORDEN DE ALLANAMIENTO'])[1]/preceding::a[1]</value>
      <webElementGuid>abc506c9-81ad-4f00-a463-0b175179958e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove_red_eye'])[1]/preceding::a[1]</value>
      <webElementGuid>71730acd-31f4-44d6-853f-d6c228a8bae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PS103']/parent::*</value>
      <webElementGuid>0e636d4d-652e-4a05-a0f4-efafee448b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>8c8e0dd6-4748-4f26-a93f-a2ac4b7eaad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell/a</value>
      <webElementGuid>550ff17e-5731-43a9-84a3-38b3a9fcee7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'mab-seleccionarModelo' and (text() = 'PS103' or . = 'PS103')]</value>
      <webElementGuid>a8d2e38c-975f-4de2-a309-d930f1310bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
