<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PS103</name>
   <tag></tag>
   <elementGuidId>cbc591be-f65d-41c7-b012-1cf39e35bcc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'PS103')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mab-seleccionarModelo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bff7105f-0063-451b-8080-cb21b133c3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>4475068d-5d9b-4648-bff5-53694de5ceef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mab-seleccionarModelo</value>
      <webElementGuid>5853282e-f01b-4583-a9d0-9fcd5150539e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>c30633b8-24f9-4046-b027-7ce1a1279d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PS103</value>
      <webElementGuid>5d812496-dc92-4047-9299-5282bd555fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mab-seleccionarModelo&quot;)</value>
      <webElementGuid>6bd6756b-c1bb-4ad8-84a6-f0066e146ab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mab-seleccionarModelo']</value>
      <webElementGuid>fd6f989a-8139-48a6-a59f-fb7d50b9eb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-cell[@id='mab-codigo']/a</value>
      <webElementGuid>3b9278ca-ae9a-4c71-86b1-a374b20d5f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PS103')]</value>
      <webElementGuid>dcacfb7a-b946-44a9-b899-1e055f74b6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vista Previa'])[1]/following::a[1]</value>
      <webElementGuid>02eb2aad-82d6-4a81-a076-d0f5fbc0def9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[1]/following::a[1]</value>
      <webElementGuid>a3e0a331-06b2-4422-91fc-fecab197f695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDEN - ORDEN DE ALLANAMIENTO'])[1]/preceding::a[1]</value>
      <webElementGuid>41a2cc35-3bb9-4176-bfd5-5ffcadf90c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove_red_eye'])[1]/preceding::a[1]</value>
      <webElementGuid>af576e91-ff73-45fe-bdfd-12e7fed24ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PS103']/parent::*</value>
      <webElementGuid>8769000b-dfd8-4683-89d5-abdecf9aa418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>d7c3c237-7ae7-43e7-97f3-5bd7faca456f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell/a</value>
      <webElementGuid>63a178b0-76d4-4422-a1d0-0099de00eaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'mab-seleccionarModelo' and (text() = 'PS103' or . = 'PS103')]</value>
      <webElementGuid>415a9cb5-93e2-4a84-9cb6-7ac9a857b12c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
