<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_get_appDescargar todo</name>
   <tag></tag>
   <elementGuidId>b09bb959-9847-49f8-87fa-b025bd40d111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-descargarTodo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='a-descargarTodo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df328122-bfe3-4002-9bc2-a90a12fcab38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger buton-style mt-3</value>
      <webElementGuid>4b253558-4731-48a0-bd28-4a5f94402ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-descargarTodo</value>
      <webElementGuid>81122f1e-0751-4714-baa8-a4d799764a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Descargar todo</value>
      <webElementGuid>d478edfd-977c-42cc-be6c-0359baaba3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20ce6f19-5e21-4403-9957-76f6952dfef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>get_appDescargar todo </value>
      <webElementGuid>c2e57b67-d793-42b7-ac0a-54fa4a897a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-descargarTodo&quot;)</value>
      <webElementGuid>15d01ec2-57cb-44b7-8dde-af098fcf9d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='a-descargarTodo']</value>
      <webElementGuid>8a170a93-f946-4dae-bb50-7596ac439eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div[2]/app-adjunto/div/button</value>
      <webElementGuid>d1076057-5f14-4102-9c4e-3630302b3b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='share'])[3]/following::button[1]</value>
      <webElementGuid>e8f08ba4-6030-4196-82e1-c10e6435beaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontró UUID de actuación'])[2]/preceding::button[1]</value>
      <webElementGuid>7bd0ad10-d4b1-43aa-b351-88d66148def2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descargar todo']/parent::*</value>
      <webElementGuid>cd480cad-47ed-48ef-af00-09225d541372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-adjunto/div/button</value>
      <webElementGuid>87853caf-2400-4058-8106-776d24c467be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'a-descargarTodo' and @title = 'Descargar todo' and @type = 'button' and (text() = 'get_appDescargar todo ' or . = 'get_appDescargar todo ')]</value>
      <webElementGuid>3566648d-e39d-4d8d-b468-20e8d713e4e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
