<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_mab-buscar</name>
   <tag></tag>
   <elementGuidId>14a6f874-bf27-494e-99db-4bd2376c362d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mab-buscar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#di-buscarModelo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fb113a9-ae76-479d-bb13-da337efff189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn boton-buscar-modelo </value>
      <webElementGuid>48040944-b639-4967-b304-58cd7ad4584f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>di-buscarModelo</value>
      <webElementGuid>cd0f5ad6-cd26-4f0f-9921-7309deaf9471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buscar Modelo</value>
      <webElementGuid>e03efc5d-9941-49cf-b71e-751c13431778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>0313ae06-58fd-4145-b58e-835fca86cc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;di-buscarModelo&quot;)</value>
      <webElementGuid>0d21378c-48b3-4cb1-a44b-c3ddf4631acb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
