<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Firmar_1</name>
   <tag></tag>
   <elementGuidId>ec6ea482-15bf-42e5-9b4b-36b4325f9e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfda-firmar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dfda-firmar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47cf92da-fc56-4f6b-bc0b-4eb23350b38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger</value>
      <webElementGuid>def4a369-c704-4d3a-9c89-5330b8ce9c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfda-firmar</value>
      <webElementGuid>1c2563b5-37be-43e9-9c65-89b901a4c772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93c2f6d9-3a08-45f3-8206-cb2023d0e90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Firmar </value>
      <webElementGuid>96ebbd24-a9f3-439d-b5b6-8b980a716e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfda-firmar&quot;)</value>
      <webElementGuid>de5cd82a-2491-4a28-8bb8-974841abdc9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dfda-firmar']</value>
      <webElementGuid>a848a401-7ee4-4b43-ac54-4d81d7f54f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='DialogoFdaComponent']/modal-accion/div/iol-dialogo-fda/div[3]/div[4]/button[2]</value>
      <webElementGuid>627546eb-949e-4b69-8d57-07631b61643b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::button[1]</value>
      <webElementGuid>05e77ab5-eb0c-4bd4-8158-2f9fa2cc9d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DGIT'])[1]/following::button[2]</value>
      <webElementGuid>ed74b591-ff27-42b8-a3ee-ffb919ed8503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>768d7d26-0b32-45b2-b2fb-c19ea21041cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dfda-firmar' and @type = 'button' and (text() = ' Firmar ' or . = ' Firmar ')]</value>
      <webElementGuid>f1c4a52f-9fdd-4081-9841-139364b3a6d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
