<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_filter_altOcultar filtros</name>
   <tag></tag>
   <elementGuidId>44ae429a-5bc3-4b4f-9388-c67d92f0ca0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mab-mostrarFiltro</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mab-mostrarFiltro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2835f906-81e2-42be-8bd3-d96da91e2103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn boton-secundario btn-sm etiqueta-estado ng-star-inserted</value>
      <webElementGuid>b2b5bc68-d02f-41ae-abb2-7c89ceaf5ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mab-mostrarFiltro</value>
      <webElementGuid>d27616a5-fe24-4ddd-b224-5b75dbc33d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10b8467c-7150-479a-a321-a6a73fef4632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>filter_altOcultar filtros </value>
      <webElementGuid>a0dbdc7c-7e7f-42cf-a01e-9f88dffaeda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mab-mostrarFiltro&quot;)</value>
      <webElementGuid>e03c511e-b9d3-458e-8104-cce64784f501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mab-mostrarFiltro']</value>
      <webElementGuid>2c293135-3501-4155-9a41-cb26c394f743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mab-modeloActuacionBuscadorForm']/button</value>
      <webElementGuid>10101ca7-056e-47bc-942f-0e49c328fd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar Modelos de Actuaciones'])[1]/following::button[1]</value>
      <webElementGuid>ea1fb40a-9610-44a6-add4-6619e75bde3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::button[1]</value>
      <webElementGuid>42601483-d52c-456f-ab48-1a533ee24c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de actuación'])[1]/preceding::button[1]</value>
      <webElementGuid>21547c59-b43d-4427-a64b-a5446fb7f1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ocultar filtros']/parent::*</value>
      <webElementGuid>c9120cce-6bd2-4fc1-8ca7-2f14cff5b160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modelo-actuacion-buscador/form/button</value>
      <webElementGuid>76ef80ea-c868-4ed9-bdfa-54c7cb539352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mab-mostrarFiltro' and @type = 'button' and (text() = 'filter_altOcultar filtros ' or . = 'filter_altOcultar filtros ')]</value>
      <webElementGuid>5cc33a60-0403-4a64-8095-fe21937a96e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
