<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_get_appDescargar todo</name>
   <tag></tag>
   <elementGuidId>b09bb959-9847-49f8-87fa-b025bd40d111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='a-descargarTodo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-descargarTodo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>164e6440-6798-4b42-aee1-7c0f2c3fc870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger buton-style mt-3</value>
      <webElementGuid>9a3e48e0-58d7-4603-b656-a49fe64d8e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-descargarTodo</value>
      <webElementGuid>ac06e983-2da3-43f9-83a5-21d28225e56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Descargar todo</value>
      <webElementGuid>aa501910-ca27-4945-8fec-65cbcf142112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e45e01b-2fbb-46ed-8649-969d547dba0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>get_appDescargar todo </value>
      <webElementGuid>d890edd0-eea5-44da-8423-d5d4d03187be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-descargarTodo&quot;)</value>
      <webElementGuid>d409e1d7-4e0a-459a-908b-5445341bc274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='a-descargarTodo']</value>
      <webElementGuid>b3dc7ed9-ac98-4cb2-a37a-b08205af95de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div[2]/app-adjunto/div/button</value>
      <webElementGuid>e73aa974-10e1-4aff-ac4b-94715c2055d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='share'])[3]/following::button[1]</value>
      <webElementGuid>7a0771a7-6bd6-439f-a3c4-8e4d126e5d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontró UUID de actuación'])[2]/preceding::button[1]</value>
      <webElementGuid>6261fa73-71b1-419b-8893-5161a0ccf971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descargar todo']/parent::*</value>
      <webElementGuid>e46b7643-e9c5-473b-bc92-befb1ced75ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-adjunto/div/button</value>
      <webElementGuid>31a90947-6210-41a6-b5a1-8666024c8337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'a-descargarTodo' and @title = 'Descargar todo' and @type = 'button' and (text() = 'get_appDescargar todo ' or . = 'get_appDescargar todo ')]</value>
      <webElementGuid>3ff85121-b046-4fab-8afe-a7f587683e6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
