<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actualizar</name>
   <tag></tag>
   <elementGuidId>95f49ca7-6be7-4857-99e3-b411981b6535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adj-actualizar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='adj-actualizar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d2ff114-e0e3-427d-96b1-36549d958330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn boton--actualizar mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>596d2339-de42-401b-9b0f-84e77f36d4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adj-actualizar</value>
      <webElementGuid>579b8131-4077-45d6-b8f7-ad81f71c5ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41987822-a41a-490c-8cdf-e9b8f45cabc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualizar</value>
      <webElementGuid>8c053902-0cf9-4609-a74e-5c00761d4f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adj-actualizar&quot;)</value>
      <webElementGuid>933305f7-64f8-4112-a9ff-2ae2134c04ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='adj-actualizar']</value>
      <webElementGuid>9a6b64e5-46d4-47b7-a221-c1f0c683731d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expand-box-header']/button</value>
      <webElementGuid>06423d48-6277-4851-8d14-f9c0e79657e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='delete'])[1]/following::button[1]</value>
      <webElementGuid>9574ef39-1665-4f01-8c8d-99a10f218723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Público'])[1]/following::button[1]</value>
      <webElementGuid>2c0c6456-fafb-4d60-80e4-3913b6bd2116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::button[1]</value>
      <webElementGuid>a5a51b49-b0d0-4e5e-83fb-8621bebbaa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-adjunto/div/div/button</value>
      <webElementGuid>3a85b16a-85a8-483a-9850-442cee4a10a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'adj-actualizar' and @type = 'button' and (text() = 'Actualizar' or . = 'Actualizar')]</value>
      <webElementGuid>cee41ee6-9b2f-4428-8941-73e368cadaf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
