<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_filter_altOcultar filtros</name>
   <tag></tag>
   <elementGuidId>44ae429a-5bc3-4b4f-9388-c67d92f0ca0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mab-mostrarFiltro']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mab-mostrarFiltro</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30137bd6-be4c-4a77-b326-6d49925ecec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn boton-secundario btn-sm etiqueta-estado ng-star-inserted</value>
      <webElementGuid>23cef747-2dbe-4b66-b65f-cc1918d4316f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mab-mostrarFiltro</value>
      <webElementGuid>89d855a6-7fea-4812-bf43-e30ea3a888ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebb9d2a0-faeb-4d01-96e0-f5703c14a116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>filter_altOcultar filtros </value>
      <webElementGuid>095c7022-1268-4f84-84b0-44a2317c411e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mab-mostrarFiltro&quot;)</value>
      <webElementGuid>1241518c-6381-4059-bf42-f4a93bf0615f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mab-mostrarFiltro']</value>
      <webElementGuid>8b4c092a-b0b6-4042-a909-6d8737ac403d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mab-modeloActuacionBuscadorForm']/button</value>
      <webElementGuid>254b9534-4f22-46ff-936d-47b5cb351689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar Modelos de Actuaciones'])[1]/following::button[1]</value>
      <webElementGuid>7f971a27-b5e9-46cc-b5c5-b64ffb01ceb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::button[1]</value>
      <webElementGuid>db830cde-2391-445b-80eb-502b420bdea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de actuación'])[1]/preceding::button[1]</value>
      <webElementGuid>b9673785-6127-4685-a6a7-a44fc642d74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ocultar filtros']/parent::*</value>
      <webElementGuid>cd0e265f-b06c-4dba-bf9a-2350646ceb89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modelo-actuacion-buscador/form/button</value>
      <webElementGuid>c9b0d3cf-d80d-4536-b3ee-469a3d2d3601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mab-mostrarFiltro' and @type = 'button' and (text() = 'filter_altOcultar filtros ' or . = 'filter_altOcultar filtros ')]</value>
      <webElementGuid>b261155d-1a6b-4eee-9c5e-06356d285ad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
