<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancelar</name>
   <tag></tag>
   <elementGuidId>351cb09e-aa26-4fe7-a4e7-0a5dc475aa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='na-cancelarStep2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#na-cancelarStep2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b14321b0-12cf-4ef4-96ec-c610fecbc668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn datos-iniciales__boton--cancelar mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>4dad5e41-8c64-453e-acd0-7e0f77200064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>na-cancelarStep2</value>
      <webElementGuid>c42b24ea-9628-494b-97d7-910a627d9859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a382215b-7d29-4cd5-8ec7-9e9aa8bd5fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>d3dc4584-90c6-47bb-88ba-5028d19d1e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;na-cancelarStep2&quot;)</value>
      <webElementGuid>861235fa-25c3-4d00-a51e-d69bc0519170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='na-cancelarStep2']</value>
      <webElementGuid>1210c225-f0a3-4a95-bc6f-2579d7064416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-1-1']/div[2]/button</value>
      <webElementGuid>c4954480-ca93-4a85-9999-76c966bea081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La suma total de los archivos a subir es de : 0.00MB'])[1]/following::button[1]</value>
      <webElementGuid>7302a108-3ed9-499c-af87-747a5077d21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subir Adjunto'])[1]/following::button[1]</value>
      <webElementGuid>cdd37159-618c-4d51-b685-3db464fcc19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar y Finalizar'])[1]/preceding::button[1]</value>
      <webElementGuid>c7cf1109-f3b0-43c7-8645-a0f36b6436d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>959f4ace-8a0d-4e85-ad6f-9ccbf60d74fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'na-cancelarStep2' and @type = 'button' and (text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>f5d1519a-bb3b-44c7-829d-feb890e8afc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
