<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add_circleCrear</name>
   <tag></tag>
   <elementGuidId>a88dca55-d280-4ffc-bceb-91261810230d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='al-crear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#al-crear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82ccc277-c50f-462e-950f-a0cf6365cfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12e47eb3-216d-4024-84f0-f8c2b154abb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>628f2285-de81-44ec-a1bd-dc1bc054eb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm mr-2 dropdown-toggle btn-crear--mobile</value>
      <webElementGuid>a79146b4-8c3f-4bd3-bf48-e45eb5599849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>96cfac68-7675-4f82-b60a-ee37c07571ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-crear</value>
      <webElementGuid>28461c6e-cc7b-47be-96c6-4ca3eec89efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Crear</value>
      <webElementGuid>48a5bc95-7e5a-441d-97b6-e394d4e3f5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57620750-93c9-4fe2-8d1d-aa646de04374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add_circleCrear</value>
      <webElementGuid>8458003a-3918-4760-a4dc-b3d3b0d5c1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-opcionSecureForm&quot;)/div[@class=&quot;secContenedor padding-lista-grilla ng-star-inserted&quot;]/div[@class=&quot;row subHeader_espacio-iconos margin-header&quot;]/div[@class=&quot;secContenedor__botones float-right&quot;]/div[@class=&quot;btn-group espacio-left_btn&quot;]/div[1]/button[@id=&quot;al-crear&quot;]</value>
      <webElementGuid>bae3f819-27aa-40e3-9dba-b4f6d52c70fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='al-crear']</value>
      <webElementGuid>07e4d7f1-1e9c-4f8e-92f0-d062e4213e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='al-opcionSecureForm']/div/div[3]/div[2]/div/div/button</value>
      <webElementGuid>2afa352f-7e05-4b09-95a7-8d2d1720fab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NES, RAM SOBRE OTROS PROCESOS SUMARISIMOS'])[1]/following::button[1]</value>
      <webElementGuid>8a7ddb74-0be9-4330-b1b5-4e008fcea180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expediente 9241/2021-0 EXP J-01-00009241-6/2021-0'])[1]/following::button[1]</value>
      <webElementGuid>b530c331-d612-435e-91e6-8b45c6abe21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/button</value>
      <webElementGuid>99d16225-5dd7-4b7f-a4a3-29d9989b1a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'al-crear' and @title = 'Crear' and @type = 'button' and (text() = 'add_circleCrear' or . = 'add_circleCrear')]</value>
      <webElementGuid>6030579f-bc06-4494-88e8-ecc9e500d67c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
