<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_shareCompartir</name>
   <tag></tag>
   <elementGuidId>8a5a7f11-a712-4abb-876b-cb6f18472f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='al-copyClipBoard'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-cell.mat-cell.cdk-column-compartir.mat-column-compartir.ng-star-inserted > #al-copyClipBoard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14ba736c-a1e5-4c0e-9b89-0d2f830ccdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn boton-secundario btn-sm ml-2 etiqueta-estado</value>
      <webElementGuid>c8a6d78e-790b-438e-a2ee-ac11a9e5ed50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-copyClipBoard</value>
      <webElementGuid>576ef327-8152-40b6-9755-093d034796e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Compartir</value>
      <webElementGuid>7c2e1765-7000-4516-b296-75a239a65bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shareCompartir </value>
      <webElementGuid>fe8360f9-765d-4ed2-abb9-29e1f8a33db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/modal-accion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body py-0&quot;]/app-adjunto[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid ng-star-inserted&quot;]/mat-table[@class=&quot;mat-table&quot;]/mat-row[@class=&quot;mat-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-column-compartir mat-column-compartir ng-star-inserted&quot;]/button[@id=&quot;al-copyClipBoard&quot;]</value>
      <webElementGuid>66641c5d-4f8e-4b7c-8024-e2fa43bc6d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='al-copyClipBoard'])[2]</value>
      <webElementGuid>2127c236-40e7-44f8-9469-2fea4aabc99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div[2]/app-adjunto/div/mat-table/mat-row/mat-cell[8]/button</value>
      <webElementGuid>f3ffd44d-2676-42a5-b8bb-07da76d76823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='get_app'])[1]/following::button[1]</value>
      <webElementGuid>785691d1-fe25-4eda-8cdc-69a6a74fe5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove_red_eye'])[3]/following::button[1]</value>
      <webElementGuid>fecbd92e-6e7e-4490-b521-9459b2d474b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba.pdf'])[2]/preceding::button[1]</value>
      <webElementGuid>c5a45fa5-f9e1-40e2-93c6-a2021f7532e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell[8]/button</value>
      <webElementGuid>ddd1f036-85e9-4ff0-91aa-dce43cfafe78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'al-copyClipBoard' and @title = 'Compartir' and (text() = 'shareCompartir ' or . = 'shareCompartir ')]</value>
      <webElementGuid>7533295e-35dd-4d5d-ab8f-7f6ce82f8744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
