<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancelar</name>
   <tag></tag>
   <elementGuidId>351cb09e-aa26-4fe7-a4e7-0a5dc475aa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#na-cancelarStep2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='na-cancelarStep2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c5adfce-325a-431c-9f74-a6f6e3ef14d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn datos-iniciales__boton--cancelar mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>4c271561-c69c-4e86-af98-6aa386458110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>na-cancelarStep2</value>
      <webElementGuid>ce1c7bd9-a63e-4b14-987c-ec3ce3e5a093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76b1c43a-faa7-498e-8d48-38751ad7e655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>8c2b4f9b-921a-466f-8909-c7d7ae5d1eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;na-cancelarStep2&quot;)</value>
      <webElementGuid>d00fb739-744a-4395-a217-31f0406969b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='na-cancelarStep2']</value>
      <webElementGuid>dd146236-bbcf-45f4-941a-1452331a2a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-1-1']/div[2]/button</value>
      <webElementGuid>a44e8460-6f07-409a-b881-7689f535b552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La suma total de los archivos a subir es de : 0.00MB'])[1]/following::button[1]</value>
      <webElementGuid>f5977c53-77b3-4e70-a580-cfedb07e5266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subir Adjunto'])[1]/following::button[1]</value>
      <webElementGuid>8bb4de87-8318-40e4-8688-601a916002f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar y Finalizar'])[1]/preceding::button[1]</value>
      <webElementGuid>0e4bf2e8-15e9-4d2a-81a6-91e3417584c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>3995f3a0-e0f0-4da5-99c3-3c208ac44fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'na-cancelarStep2' and @type = 'button' and (text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>3b729fc6-8365-4736-9978-44c789ea7439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
