<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_shareCompartir</name>
   <tag></tag>
   <elementGuidId>8a5a7f11-a712-4abb-876b-cb6f18472f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='al-copyClipBoard'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-cell.mat-cell.cdk-column-compartir.mat-column-compartir.ng-star-inserted > #al-copyClipBoard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c9c8a77-77c7-465b-8901-e9fa74b2d3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn boton-secundario btn-sm ml-2 etiqueta-estado</value>
      <webElementGuid>4ed7d6b5-60ac-422d-8e47-ee56c4565d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-copyClipBoard</value>
      <webElementGuid>23b854ac-0836-46df-a467-cf0c613637cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Compartir</value>
      <webElementGuid>9f2a9754-97b9-4dec-a345-121b7dac69c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shareCompartir </value>
      <webElementGuid>1f7a95df-a2c5-4f58-9eaa-2c4fef4dcdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/modal-accion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body py-0&quot;]/app-adjunto[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid ng-star-inserted&quot;]/mat-table[@class=&quot;mat-table&quot;]/mat-row[@class=&quot;mat-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-column-compartir mat-column-compartir ng-star-inserted&quot;]/button[@id=&quot;al-copyClipBoard&quot;]</value>
      <webElementGuid>ab53a0da-2357-480e-ba09-7827e299235a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='al-copyClipBoard'])[2]</value>
      <webElementGuid>3c6a1508-60a6-4ac8-84d8-47c07c883ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div[2]/app-adjunto/div/mat-table/mat-row/mat-cell[8]/button</value>
      <webElementGuid>8806a1ce-c0f5-4dd1-9279-ade442268e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='get_app'])[1]/following::button[1]</value>
      <webElementGuid>7b83d14a-922c-4872-b2d8-71b7567d80c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove_red_eye'])[3]/following::button[1]</value>
      <webElementGuid>5dbc9286-9fa2-48df-ac70-8f02068007e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba.pdf'])[2]/preceding::button[1]</value>
      <webElementGuid>a2921f38-6e52-4dde-8396-b7055fa20381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell[8]/button</value>
      <webElementGuid>599aa7a6-c6fa-4ca2-952b-d5c98dfc10e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'al-copyClipBoard' and @title = 'Compartir' and (text() = 'shareCompartir ' or . = 'shareCompartir ')]</value>
      <webElementGuid>8904de65-a1de-461b-8ce9-594d29afff58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
