<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Firmar</name>
   <tag></tag>
   <elementGuidId>df136b00-54ef-4f8e-8996-7fd91e63b124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='al-firmar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#al-firmar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65e9dda9-ed47-4333-89da-592468126cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17b020f9-825b-4933-9e41-a2c60b62faa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e65f5ff-63c8-4de9-aa88-38dac4dbc852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm ml-2 etiqueta-estado btn-disabled</value>
      <webElementGuid>7e7ebffb-24e9-41c7-8c48-b52da142c0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>5aef6892-6472-4668-958c-296bbcb3e75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-firmar</value>
      <webElementGuid>6f6b222c-7da5-4dac-91aa-dc03532fc317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Firmar</value>
      <webElementGuid>ab3a018e-ec63-4fef-a979-44a22d5a603b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fb5a6e1-093a-41e2-a594-bc23d665e02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Firmar </value>
      <webElementGuid>b184ea76-d7ac-48e6-a631-c2d86a839ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-firmar&quot;)</value>
      <webElementGuid>38c30642-5c41-4865-a801-1339504bd53b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='al-firmar']</value>
      <webElementGuid>98aed9da-5854-4bea-839d-c2c06d64dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilidad'])[1]/following::button[1]</value>
      <webElementGuid>7a4de8e3-cbbc-4338-ab94-5c57066382b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Actuación'])[1]/following::button[2]</value>
      <webElementGuid>f6007d2c-0655-4dc3-9415-9c30381aff28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con token'])[1]/preceding::button[1]</value>
      <webElementGuid>f92063ae-4310-4a5a-a5d7-bc770834b7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/button</value>
      <webElementGuid>68539a65-e31d-480c-bc6a-c5d64196d357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'al-firmar' and @title = 'Firmar' and @type = 'button' and (text() = ' Firmar ' or . = ' Firmar ')]</value>
      <webElementGuid>ca2e9640-5614-4e95-a8bc-e15f6c00a6b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
