<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eliminar Actuacin</name>
   <tag></tag>
   <elementGuidId>054cc982-cdd0-411b-804c-dc140d2e2969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#al-eliminaract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='al-eliminaract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>729ac0f7-0419-4481-a4b2-59862a1df0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-item btn-sm</value>
      <webElementGuid>24003eaf-4e90-4a7d-aaf6-d49a2e1f4248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-eliminaract</value>
      <webElementGuid>05bd4ef1-d443-4301-b257-9a58beacf4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar Actuación</value>
      <webElementGuid>c9c76b4f-c0ff-4913-ae31-c609e6d937f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-eliminaract&quot;)</value>
      <webElementGuid>ccdc868f-f295-4e00-ab53-8e62aec6c96a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='al-eliminaract']</value>
      <webElementGuid>8710198c-1635-47df-b410-8ee8945828c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver Auditoría'])[1]/following::button[1]</value>
      <webElementGuid>e80db566-d50c-461d-bc9f-c5ef8285824b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more_vert'])[1]/following::button[2]</value>
      <webElementGuid>16586acb-ed31-4b11-8136-cf5808a4ae8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilidad'])[1]/preceding::button[1]</value>
      <webElementGuid>3dd85ed5-044d-4ce6-8a11-beec1654e8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar'])[1]/preceding::button[2]</value>
      <webElementGuid>6348234b-8bd5-4b3e-b6bb-38ee939e4464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eliminar Actuación']/parent::*</value>
      <webElementGuid>26011f19-3da6-47ed-9bbc-f86879048b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>caaa0a94-177f-49c3-9aae-1096d80be865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'al-eliminaract' and (text() = 'Eliminar Actuación' or . = 'Eliminar Actuación')]</value>
      <webElementGuid>b270dd1a-edac-46a1-8384-20ee9b44d22d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
