<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EXP J-01-00009241-62021-0</name>
   <tag></tag>
   <elementGuidId>1a8ab21c-cdc7-47e8-a295-13e844bd8b96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dfda-infoExp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfda-infoExp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76bf663d-050a-4c72-a2f1-db8da080c72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secContenedor__titulo float-left secContenedor__botonesListAct--margin</value>
      <webElementGuid>24c39ec5-9ebb-42b6-95e8-79b74da30c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfda-infoExp</value>
      <webElementGuid>c9095a8a-85b0-40d6-a703-eab295bd5958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXP J-01-00009241-6/2021-0</value>
      <webElementGuid>463437bf-85e1-4498-9b56-444c017903a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfda-infoExp&quot;)</value>
      <webElementGuid>eab60a63-6978-438c-9091-733a9ae89ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dfda-infoExp']</value>
      <webElementGuid>31f464fe-2ea8-42c8-b656-983884a5e772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='DialogoFdaComponent']/modal-accion/div/iol-dialogo-fda/div[2]/div/div</value>
      <webElementGuid>b39dee42-907d-4b38-a52c-f749c2e02d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firma Digital'])[1]/following::div[3]</value>
      <webElementGuid>dbc3212d-f101-4c5e-90bf-76f70b5e53d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::div[12]</value>
      <webElementGuid>60456d63-1b6f-4c76-a963-971b437babd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actuación: 43566/2022'])[1]/preceding::div[1]</value>
      <webElementGuid>217bad10-33f9-49a8-b446-2369640e4586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nestor firma1'])[1]/preceding::div[11]</value>
      <webElementGuid>e5dc3c5e-12b5-4391-b256-c8ffa3029178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EXP J-01-00009241-6/2021-0']/parent::*</value>
      <webElementGuid>d01df6b7-a9ed-4324-829d-54c9960115e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iol-dialogo-fda/div[2]/div/div</value>
      <webElementGuid>8caf3ae6-b7cc-45f4-a754-3493827621b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dfda-infoExp' and (text() = 'EXP J-01-00009241-6/2021-0' or . = 'EXP J-01-00009241-6/2021-0')]</value>
      <webElementGuid>56621573-b5ff-4af7-99a8-b9a6adbbe54f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
