<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_attach_file</name>
   <tag></tag>
   <elementGuidId>51b0a060-9d7a-4fa9-8b25-ade322f92caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//em[@id='la-actualizar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#la-actualizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>6e2faebd-593b-4170-a008-07c269ee6311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons secContenedor__botones--vista-c botones--tarjeta</value>
      <webElementGuid>4ec753df-b549-43cc-b664-469fac275392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>la-actualizar</value>
      <webElementGuid>73a27039-5808-4558-a83c-8c77f08da9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>attach_file</value>
      <webElementGuid>00c66e1c-2d24-4f6c-9d25-1cb00f71f767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;la-actualizar&quot;)</value>
      <webElementGuid>d7adee8d-d9d5-4740-884d-0a5341f789b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//em[@id='la-actualizar']</value>
      <webElementGuid>2875dcdb-8743-4c37-9b03-2e1bef7951b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='al-verAdjunto']/div/em</value>
      <webElementGuid>18b5f2ee-a9cc-460c-954b-e2f4aba51a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create'])[1]/following::em[1]</value>
      <webElementGuid>db45640d-cc43-4c5d-86f0-9f1b7e5f32bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BORRADOR'])[1]/preceding::em[1]</value>
      <webElementGuid>d3bff79a-01eb-4bd3-b40b-fb84dbbb3798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BC'])[1]/preceding::em[1]</value>
      <webElementGuid>6f431b23-1117-4e72-8825-773c07272664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='attach_file']/parent::*</value>
      <webElementGuid>b02e6327-6a41-42a7-8134-9551ec26cb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/em</value>
      <webElementGuid>cd0aae89-735e-486a-90a8-2ca9d3c08f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[@id = 'la-actualizar' and (text() = 'attach_file' or . = 'attach_file')]</value>
      <webElementGuid>89ba75eb-98a5-4bc8-9dc1-1d38779b3125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
