<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_attach_file</name>
   <tag></tag>
   <elementGuidId>51b0a060-9d7a-4fa9-8b25-ade322f92caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//em[@id='la-actualizar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#la-actualizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>d2b2c901-94fb-4b66-9880-0b35a600ee96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons secContenedor__botones--vista-c botones--tarjeta</value>
      <webElementGuid>b0d889dc-baf9-4ced-b1ce-334d6a7c19ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>la-actualizar</value>
      <webElementGuid>8eb28900-e6bc-4549-bc17-3a08af4890b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>attach_file</value>
      <webElementGuid>4f2753c9-5dd1-47a2-a6eb-93b9db1098bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;la-actualizar&quot;)</value>
      <webElementGuid>c5d655c0-4590-4b36-a407-b76625706736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//em[@id='la-actualizar']</value>
      <webElementGuid>95fec874-2fdb-4242-9766-31c7f28d725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='al-verAdjunto']/div/em</value>
      <webElementGuid>158539d8-3fbf-423e-a8e4-e5cd566df3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create'])[1]/following::em[1]</value>
      <webElementGuid>8e5745b6-ad6c-4a44-be2a-14231aeb43a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BORRADOR'])[1]/preceding::em[1]</value>
      <webElementGuid>940661ac-8ad1-49ef-b21a-eca8b857553f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BC'])[1]/preceding::em[1]</value>
      <webElementGuid>79b0c9f1-0193-49ee-ab82-fa2b61ef0681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='attach_file']/parent::*</value>
      <webElementGuid>835e1990-1e20-417c-9ab5-57635bccf946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/em</value>
      <webElementGuid>ae0329e5-9abc-467b-a866-438938133e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[@id = 'la-actualizar' and (text() = 'attach_file' or . = 'attach_file')]</value>
      <webElementGuid>859a8078-814a-4909-baa7-16c005d947e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
