<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_delete</name>
   <tag></tag>
   <elementGuidId>cb0f20b1-eb5e-48a0-a74a-be0bd97f1638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//em[. = 'delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expand-box-header > #al-verAdjunto > div > #la-actualizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>73a3bc25-e139-4d3d-89ae-e37c9809f547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons secContenedor__botones--vista-c botones--tarjeta</value>
      <webElementGuid>edd0ac21-9048-43b8-805c-ba518ce1ac38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>98f87fe2-bd72-466e-adef-45828083dddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>above</value>
      <webElementGuid>0a22642c-5b7a-41d4-9aa8-8117a1aae669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>78780da6-e41b-46c3-bc97-9deae4d173bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expand-box-header&quot;)/a[@id=&quot;al-verAdjunto&quot;]/div[1]/em[@id=&quot;la-actualizar&quot;]</value>
      <webElementGuid>32aeb2bc-b27b-49a1-9699-674cf4fb6edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>la-actualizar</value>
      <webElementGuid>6abedc5e-dc4d-4fe1-8ae3-e55a76871251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//em[@id='la-actualizar'])[2]</value>
      <webElementGuid>960dbd08-eaaf-4be0-a58c-9783ed7505c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='al-verAdjunto']/div/em)[2]</value>
      <webElementGuid>7c6a5b05-f0bb-4ee6-b114-b98819147189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Público'])[1]/following::em[1]</value>
      <webElementGuid>0bbbe6d0-fd4d-440d-af2a-98bbe4a1c534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Acceso'])[1]/following::em[1]</value>
      <webElementGuid>1e2921ca-dbe3-4d8a-b088-f0157fd9eb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actualizar'])[1]/preceding::em[1]</value>
      <webElementGuid>a749f7da-324e-4ae8-a71e-ef27a8ebf4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::em[1]</value>
      <webElementGuid>adedd847-1e4b-4901-8a6d-3853feb636ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='delete']/parent::*</value>
      <webElementGuid>5f95fc88-61a2-47b8-8be4-6c6dc7f62b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-adjunto/div/div/a/div/em</value>
      <webElementGuid>77d34880-58c2-45d9-bc95-26649f6c0bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[@id = 'la-actualizar' and (text() = 'delete' or . = 'delete')]</value>
      <webElementGuid>43e3b491-a6dc-400a-b641-40f21ef59ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='sa-eliminar']/em</value>
      <webElementGuid>a99945f3-2322-4aa3-8d44-576b9a08840b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subir Adjunto'])[1]/following::em[1]</value>
      <webElementGuid>c7c6f3d8-a8fd-478d-830b-a6004ee917b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La presentación total no puede superar los 5 MB'])[1]/following::em[1]</value>
      <webElementGuid>6703c148-d2aa-4b03-8875-65f3f01eb66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba.pdf'])[1]/preceding::em[1]</value>
      <webElementGuid>4bc25300-29e3-4bba-ad51-664b108193e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/em</value>
      <webElementGuid>bc2b0a4d-87ea-4e13-8008-e7c4cb691c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'delete' or . = 'delete')]</value>
      <webElementGuid>7530289d-485c-4bd2-be03-51776af88be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
