<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_delete</name>
   <tag></tag>
   <elementGuidId>cb0f20b1-eb5e-48a0-a74a-be0bd97f1638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//em[. = 'delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expand-box-header > #al-verAdjunto > div > #la-actualizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>fd3b6f32-efee-455c-b09e-c3a277ab88be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons secContenedor__botones--vista-c botones--tarjeta</value>
      <webElementGuid>53f6d3ac-cb87-4f0d-b785-0a88a1b8f53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>86edb8b9-71c5-437f-a4f8-0369f3d34ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>above</value>
      <webElementGuid>5dc62234-f0e5-4dca-82e9-a4eca7cbf8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>2aa139d4-86cc-4ef7-a62a-d847978cf8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expand-box-header&quot;)/a[@id=&quot;al-verAdjunto&quot;]/div[1]/em[@id=&quot;la-actualizar&quot;]</value>
      <webElementGuid>90d13e54-6e93-4163-bacd-94787f124230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>la-actualizar</value>
      <webElementGuid>8e627e0c-fc6d-4b07-a187-4752eca64c3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//em[@id='la-actualizar'])[2]</value>
      <webElementGuid>8a9f8b3c-e3fa-402f-aab7-6aa802944da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='al-verAdjunto']/div/em)[2]</value>
      <webElementGuid>265fe9fd-cf12-494e-9cb1-75f62cb84a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Público'])[1]/following::em[1]</value>
      <webElementGuid>2034b233-6e5b-46a7-a535-1d347020fd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Acceso'])[1]/following::em[1]</value>
      <webElementGuid>b5592685-18ef-49a5-a612-99b20bf8e32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actualizar'])[1]/preceding::em[1]</value>
      <webElementGuid>015bb3f1-337d-4d3e-9098-934569882bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::em[1]</value>
      <webElementGuid>79adbbfc-bb00-4892-b3ef-d00019f337fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='delete']/parent::*</value>
      <webElementGuid>fc6863f4-e41a-4d0a-af20-9e996b7cff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-adjunto/div/div/a/div/em</value>
      <webElementGuid>141ece28-8ef0-40de-8167-aad0da8e4ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[@id = 'la-actualizar' and (text() = 'delete' or . = 'delete')]</value>
      <webElementGuid>60934083-e2b7-4dd9-b805-9e9e17761220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='sa-eliminar']/em</value>
      <webElementGuid>b9e4428f-ce76-4822-babc-e2d705be2e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subir Adjunto'])[1]/following::em[1]</value>
      <webElementGuid>8eb0cf54-9187-42c4-bb86-e58a310ceeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La presentación total no puede superar los 5 MB'])[1]/following::em[1]</value>
      <webElementGuid>0aa748f9-d666-4fda-88b0-cdbcb4068928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba.pdf'])[1]/preceding::em[1]</value>
      <webElementGuid>fbb65617-d00d-433d-bcaf-11c7a270d51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/em</value>
      <webElementGuid>f746e617-aff8-4e9a-997a-155201e87663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'delete' or . = 'delete')]</value>
      <webElementGuid>e0b52b4b-a29e-4854-94f1-e7a87657ac25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
