<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Adjuntos de la actuacin 436402022</name>
   <tag></tag>
   <elementGuidId>65d09c03-7000-4e9b-b22a-c8ddc31f834f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='ma-titulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ma-titulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>295b8b29-5ef0-46ac-be00-7ceb12e2d573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ma-titulo</value>
      <webElementGuid>7c63c7fb-e1c5-4031-a7e3-1b79a98e0e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adjuntos de la actuación 43640/2022</value>
      <webElementGuid>9d04fad3-2f6d-4f30-935b-69793b66aa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ma-titulo&quot;)</value>
      <webElementGuid>88169378-88c4-44fb-bad9-874e836b5f8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='ma-titulo']</value>
      <webElementGuid>f912b21b-1bf2-4c3c-a863-5e9f2fda4dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div/div/h4</value>
      <webElementGuid>00c2e890-d988-439f-a72b-830ae4565118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::h4[1]</value>
      <webElementGuid>6da505e7-5663-4f73-9854-5c8d39a81770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::h4[1]</value>
      <webElementGuid>e7437b01-7697-4ccd-878d-a724deb0dc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[1]/preceding::h4[1]</value>
      <webElementGuid>cea406e5-eec4-4cbf-b1e6-21175c6d93f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuario'])[1]/preceding::h4[1]</value>
      <webElementGuid>dcd74ff0-e949-4b42-a0fe-fd69ecf18805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adjuntos de la actuación 43640/2022']/parent::*</value>
      <webElementGuid>702e16f8-99ec-4c8c-a8ae-01c60c421b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>75d1691e-e3d6-484d-b000-64b0686d6ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'ma-titulo' and (text() = 'Adjuntos de la actuación 43640/2022' or . = 'Adjuntos de la actuación 43640/2022')]</value>
      <webElementGuid>849f03f9-acf7-43e4-85de-06eebcee0af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
