<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Adjuntos de la actuacin 436402022</name>
   <tag></tag>
   <elementGuidId>65d09c03-7000-4e9b-b22a-c8ddc31f834f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='ma-titulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ma-titulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5521cf40-c1a3-427b-853e-7be03fb4732f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ma-titulo</value>
      <webElementGuid>c1943dae-dd7e-4611-a1fb-b210660ebbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adjuntos de la actuación 43640/2022</value>
      <webElementGuid>db28367b-8285-4e20-b5dc-fa0065b5d5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ma-titulo&quot;)</value>
      <webElementGuid>82db895c-3c2c-49c2-a41f-af05fb9afba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='ma-titulo']</value>
      <webElementGuid>403f2aff-0229-46c7-8175-58b20133518a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div/div/h4</value>
      <webElementGuid>d2253be3-5fe1-4362-86b3-eeb9545aef96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::h4[1]</value>
      <webElementGuid>ebb968a4-d1f2-47e9-a66c-96465e07d7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::h4[1]</value>
      <webElementGuid>65f44bf4-8e67-4ed0-ab46-9a4c7e332910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[1]/preceding::h4[1]</value>
      <webElementGuid>56d22943-67ee-47b4-8ba4-6b24307a7e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuario'])[1]/preceding::h4[1]</value>
      <webElementGuid>8bbee676-757d-462c-9f7b-a7f86203fb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adjuntos de la actuación 43640/2022']/parent::*</value>
      <webElementGuid>255fbb78-405c-41f5-8d70-df530b788131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>4b95b8da-12de-41f6-9f81-196850f31bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
