<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Buscar Modelos de Actuaciones</name>
   <tag></tag>
   <elementGuidId>dbf02c50-9a34-45b3-96a5-2d4256db1dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='ma-titulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ma-titulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d78e9c02-c5e2-41b6-9372-db4f49f2111c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ma-titulo</value>
      <webElementGuid>a6c54103-f8c1-4ad5-b0a7-48e4c3adab2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar Modelos de Actuaciones</value>
      <webElementGuid>968eb619-6e7c-41d7-ad83-0370daba7fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ma-titulo&quot;)</value>
      <webElementGuid>eee69dec-04d8-4216-90c7-1cefd919c07c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='ma-titulo']</value>
      <webElementGuid>d521138c-e9a3-45ba-b06d-c95978aa36a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/modal-accion/div/div/h4</value>
      <webElementGuid>a519e745-7056-402c-81c5-dda36db324ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::h4[1]</value>
      <webElementGuid>6f73c78d-fbb8-42d1-98da-9fef3cdbf1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::h4[1]</value>
      <webElementGuid>d66651cc-312a-47b2-861c-5ff165b43c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='filter_alt'])[1]/preceding::h4[1]</value>
      <webElementGuid>02344543-352b-4d82-9a3d-f8bff39c04e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar Modelos de Actuaciones']/parent::*</value>
      <webElementGuid>db1f2b76-7b48-4201-bb2f-451dba53ef50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>2dd45c41-928a-4a05-bfbb-b81988167251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'ma-titulo' and (text() = 'Buscar Modelos de Actuaciones' or . = 'Buscar Modelos de Actuaciones')]</value>
      <webElementGuid>54772cc2-97ea-4cd5-a1b2-d8a26d608851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
