<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Firma Digital</name>
   <tag></tag>
   <elementGuidId>7a9d54eb-8ede-4c3d-a014-b3e23c0e3bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='ma-titulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ma-titulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f200ed51-f0cf-4890-b0de-6f8718d7f50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ma-titulo</value>
      <webElementGuid>93605a39-59fe-464c-b4b7-330b32765bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Firma Digital</value>
      <webElementGuid>d6d8ad9f-0c61-4e48-98a5-42fc2ff48676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ma-titulo&quot;)</value>
      <webElementGuid>8609a4ab-826f-4a11-8407-70207d704893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='ma-titulo']</value>
      <webElementGuid>372e4fd8-b03f-4b8c-99ae-462bb539f583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='DialogoFdaComponent']/modal-accion/div/iol-dialogo-fda/div/div/h4</value>
      <webElementGuid>c4780eb5-5804-492e-86a6-9d78e703c5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::h4[1]</value>
      <webElementGuid>4949a2e6-64cd-4c4e-9533-16ef0a1fa6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ma-titulo', '&quot;', ')')])[1]/following::h4[1]</value>
      <webElementGuid>d0ace2bb-3123-4683-b771-32df5580b68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXP J-01-00009241-6/2021-0'])[1]/preceding::h4[1]</value>
      <webElementGuid>da208afa-b663-4fcf-9b57-01c08b45009f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actuación: 43566/2022'])[1]/preceding::h4[1]</value>
      <webElementGuid>74b72c22-5817-4e10-af11-892e323e7e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Firma Digital']/parent::*</value>
      <webElementGuid>b87cf82a-0b13-4fe0-968c-8b138367e996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>25f6e402-f59e-426f-b267-5e03d956c80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'ma-titulo' and (text() = 'Firma Digital' or . = 'Firma Digital')]</value>
      <webElementGuid>dcfc885c-545f-4d37-b60d-89281b44d2f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
