<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Firma Digital</name>
   <tag></tag>
   <elementGuidId>7a9d54eb-8ede-4c3d-a014-b3e23c0e3bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='ma-titulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ma-titulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f803fa42-bee4-45bf-9dcc-aa1ddb763e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ma-titulo</value>
      <webElementGuid>380626c4-a2fc-4b3d-afdd-6e677fe376a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Firma Digital</value>
      <webElementGuid>6bbeb9ee-1a0c-4287-9344-0e05f4cbce53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ma-titulo&quot;)</value>
      <webElementGuid>a2046690-b844-48d2-bd16-5cd7e906ab91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='ma-titulo']</value>
      <webElementGuid>7600075c-234e-4d01-a11e-9f0b36dda745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='DialogoFdaComponent']/modal-accion/div/iol-dialogo-fda/div/div/h4</value>
      <webElementGuid>2636cabc-4dbc-474b-b3e5-a4e3823f5f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::h4[1]</value>
      <webElementGuid>75b5295f-8474-48cf-892d-b3379cbfd2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ma-titulo', '&quot;', ')')])[1]/following::h4[1]</value>
      <webElementGuid>a866db11-5917-44b3-abc9-0d4d3337e319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXP J-01-00009241-6/2021-0'])[1]/preceding::h4[1]</value>
      <webElementGuid>5f9fc843-03a6-4eb9-b4bd-2df15a20852e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actuación: 43566/2022'])[1]/preceding::h4[1]</value>
      <webElementGuid>125dfc38-4859-49a0-a256-c4eb2606f795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Firma Digital']/parent::*</value>
      <webElementGuid>b2469505-f50e-4611-8daa-3ca6e338f3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>0ab58449-1e2d-488a-a343-c4c6344e6135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'ma-titulo' and (text() = 'Firma Digital' or . = 'Firma Digital')]</value>
      <webElementGuid>7f441fa2-98d8-414b-87b5-edae94538013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
