<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subir Adjunto_sa-fileInput</name>
   <tag></tag>
   <elementGuidId>4da8b61d-9577-4ec0-bb0c-dac9e983aa2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sa-fileInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sa-fileInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef327910-9505-4f8e-8f44-b9b419cb9e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sa-fileInput</value>
      <webElementGuid>d70b2f6e-a7a5-4290-85a4-a1047e5b8a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>menu-close</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>836b68cb-d664-44ed-93f6-a3a588de4eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>fe4b4413-a556-4528-aed0-734f5ebbde40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>5f199d70-345b-4032-88aa-dcd52bb59f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sa-fileInput&quot;)</value>
      <webElementGuid>ad5027f6-1dac-49e1-8ef6-fb3d39c4ba9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sa-fileInput']</value>
      <webElementGuid>ded77977-1d5e-4af1-b55d-e57aa25c33fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-1-1']/div/iol-selector-archivo/div/div[2]/span/input</value>
      <webElementGuid>5398baa3-8140-459a-8aaf-f1d8c73d2b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>b2a99dbb-577d-4065-a44e-652f3bd3afeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sa-fileInput' and @type = 'file']</value>
      <webElementGuid>126fb5b3-d262-4602-a143-78ec07c2ae77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
