<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Importar Actuacin_sa-fileInput</name>
   <tag></tag>
   <elementGuidId>8007342c-6c51-4950-8c95-c06b181d404f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sa-fileInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sa-fileInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f41bbbe9-36ae-48c5-a8f8-7a84019d4c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sa-fileInput</value>
      <webElementGuid>912c0bb5-0d25-40d8-84b6-a703868a9595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>menu-close</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e025152a-5de8-4975-8e42-b2ce2911a211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>05a39094-1dc8-4bed-9020-edf7909e3699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sa-fileInput&quot;)</value>
      <webElementGuid>6f3c9b3c-7075-4050-bb30-c37a44493249</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sa-fileInput']</value>
      <webElementGuid>587bed2e-319a-4ae6-9aa6-d56291935419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7e46f5a2-7419-40dc-8b42-d41ddeca7df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sa-fileInput' and @type = 'file']</value>
      <webElementGuid>8fd60562-632c-4e7c-9192-7cedf3fdff1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
