<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_filter_alt_codigo</name>
   <tag></tag>
   <elementGuidId>fde977f9-8fcd-4662-8666-f713a8ce480f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mab-ingresarCodigo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-form-field[@id='prueba']/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7c03151-c0db-4ebc-91a6-bee257a3cf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1422afd2-ccdc-45ae-b267-653b3d842ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>codigo</value>
      <webElementGuid>62bcc0e6-54a9-47dc-96d2-e2099217b25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mab-ingresarCodigo</value>
      <webElementGuid>44d2cbf2-99ed-49c5-ae1e-a18f07382b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codigo</value>
      <webElementGuid>8b3bb6c4-b73d-4715-b1ad-61f4eb9cd93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase()</value>
      <webElementGuid>6a870bb0-c3b5-47f2-9a95-b056382ab8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>a959629f-2737-4c88-940e-5efdbbc0b58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c373f1c-dd4a-45bc-b1c1-b3bd2c43fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3f51594b-a7af-40f8-ad5f-8e4502033191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a1d681b-9f54-449e-997f-f6619589c705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mab-ingresarCodigo&quot;)</value>
      <webElementGuid>aad82139-c5d8-49ec-a37d-bad7c6332d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mab-ingresarCodigo']</value>
      <webElementGuid>8b50e7a9-37e5-43be-a73e-32379b1aac7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-form-field[@id='prueba']/div/div/div[3]/input</value>
      <webElementGuid>83cad14d-4b98-4e93-987c-84d4cd752cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>c7b7349c-13e8-43d9-a6f2-8b91f2f1266e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mab-ingresarCodigo' and @name = 'codigo' and @placeholder = 'Código' and @type = 'text']</value>
      <webElementGuid>cb064a71-061e-4ac3-acc9-205f93f8aed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
