<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subir Adjunto_sa-fileInput</name>
   <tag></tag>
   <elementGuidId>4da8b61d-9577-4ec0-bb0c-dac9e983aa2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sa-fileInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sa-fileInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c56a7a8-dbc4-46f7-8bc4-903c31fd3364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sa-fileInput</value>
      <webElementGuid>3e05b5c6-3581-4d6f-91cb-79f5782f5466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>menu-close</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>586f96c6-8873-49ff-9433-73a38b787be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>7d49ab75-d6fb-4506-b9e9-894b8c7f898e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>d37d8966-6c0d-43a8-9d9a-50baac1c0d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sa-fileInput&quot;)</value>
      <webElementGuid>0a4c6ed1-8f56-4bba-89ae-2e8ba155772d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sa-fileInput']</value>
      <webElementGuid>374d515f-ab59-4eb1-bef0-3fa5e25eaafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-1-1']/div/iol-selector-archivo/div/div[2]/span/input</value>
      <webElementGuid>cdbf161e-89a4-419c-b7d1-46a15b30fd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>590d0908-b48f-407d-83d7-6a8347b05090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sa-fileInput' and @type = 'file']</value>
      <webElementGuid>b31f78d1-3f70-4ced-8078-442971f73efe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
