<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subir Adjunto_sa-fileInput</name>
   <tag></tag>
   <elementGuidId>4da8b61d-9577-4ec0-bb0c-dac9e983aa2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sa-fileInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sa-fileInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11a83197-7c85-418a-9a03-a0653b543254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sa-fileInput</value>
      <webElementGuid>bca82c70-9379-4e7a-94f9-7dacff3016ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>menu-close</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7735651b-4e17-45f4-9ec2-8619aacdde43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>17dad7bb-17c4-4730-9401-138e2b1cf4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>a059206d-f40f-45e5-a13a-c53b07b5a8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sa-fileInput&quot;)</value>
      <webElementGuid>e1e7bd6e-9f41-48fd-a5a6-044cc2119031</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sa-fileInput']</value>
      <webElementGuid>1f6e106c-793b-47e5-9a76-a11fb6bf7ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-1-1']/div/iol-selector-archivo/div/div[2]/span/input</value>
      <webElementGuid>5af7d7ea-f4f4-4969-9d9a-9f75211fd2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>6d43b217-2411-4692-8ed9-95c0f6533b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sa-fileInput' and @type = 'file']</value>
      <webElementGuid>caafb8b2-1cea-4e30-a710-8e194dbd8689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
