<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Importar Actuacin_sa-fileInput</name>
   <tag></tag>
   <elementGuidId>8007342c-6c51-4950-8c95-c06b181d404f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sa-fileInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sa-fileInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff896846-6b53-4267-a122-ff2e2a9dd79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sa-fileInput</value>
      <webElementGuid>98c807aa-d2b1-4f82-bc72-ed43bffb7c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>menu-close</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94abb9fd-9d27-426d-a838-77e9022d69f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>26751037-178a-499b-b745-8f35beaba9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sa-fileInput&quot;)</value>
      <webElementGuid>e72387b7-5b9f-4729-98c5-6751e83b424c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sa-fileInput']</value>
      <webElementGuid>18259f83-1a54-4ea2-b86d-9820fd94d238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>686b0a4d-8b66-4731-87d2-933259337f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sa-fileInput' and @type = 'file']</value>
      <webElementGuid>15fb78d0-b1ec-4654-a202-9a91bb59d10b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
