<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nombre del adjunto</name>
   <tag></tag>
   <elementGuidId>fcb7781f-c96d-4939-b9dc-2826ae643db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.adjunto_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='adj-adjuntoForm']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>416d9261-26a3-4961-aa75-f87b2f0c7206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>adjunto_label</value>
      <webElementGuid>6b61d2ca-0a69-4025-8df3-a005ea3b55d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nombre del adjunto</value>
      <webElementGuid>1393be8f-86c5-4696-ae0f-b8cefbde59b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adj-adjuntoForm&quot;)/div[@class=&quot;mb-2&quot;]/label[@class=&quot;adjunto_label&quot;]</value>
      <webElementGuid>7ac5fd25-e4e3-4534-8fc3-98a4099fe241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adj-adjuntoForm']/div/label</value>
      <webElementGuid>77897445-ff0e-4d14-ac31-0c3a825f013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjuntos de la actuación 43640/2022'])[1]/following::label[1]</value>
      <webElementGuid>20a2b21c-57ea-4b01-9678-24dfbe27e314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::label[1]</value>
      <webElementGuid>c6ffd151-a188-4144-b8ba-fe3d0a30edf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Acceso'])[1]/preceding::label[1]</value>
      <webElementGuid>987e8794-ba7f-424a-b820-959969a757e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Público'])[1]/preceding::label[2]</value>
      <webElementGuid>3cb8e7df-28b0-472d-9bd1-84bd6c945056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nombre del adjunto']/parent::*</value>
      <webElementGuid>ae00ff22-e0fb-4a78-ae44-efd5c3cb8819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/label</value>
      <webElementGuid>cb81dc72-ebcb-4de6-ae4f-1952083ca722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nombre del adjunto' or . = 'Nombre del adjunto')]</value>
      <webElementGuid>d1c7526f-0f19-4de2-a937-e7a0d997cb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjuntos de la actuación 43566/2022'])[1]/following::label[1]</value>
      <webElementGuid>d0c9632f-778e-4011-9a0c-81b3f9de090e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
