<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-row_deletePrueba.pdfPblico Privado</name>
   <tag></tag>
   <elementGuidId>eb82f51c-0902-4943-a480-6965bfdcbac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-0-1']/div/iol-selector-archivo/div/div[3]/div/mat-table/mat-row</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-row.mat-row.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-row</value>
      <webElementGuid>f12208b4-1479-422e-88eb-97254850ea1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-row ng-star-inserted</value>
      <webElementGuid>7a5f5438-f188-4935-9c7f-59f75a793b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>6006072d-a6f0-414b-afd7-cd93379bc9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>deletePrueba.pdf Público  Privado </value>
      <webElementGuid>35490c8d-dc28-4681-ae4a-cf74cfc9b76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-1&quot;)/div[@class=&quot;ng-star-inserted&quot;]/iol-selector-archivo[1]/div[1]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/mat-table[@class=&quot;files-table' mat-table ng-star-inserted&quot;]/mat-row[@class=&quot;mat-row ng-star-inserted&quot;]</value>
      <webElementGuid>ac97a650-cdb6-40da-b143-16e3bb475c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-1']/div/iol-selector-archivo/div/div[3]/div/mat-table/mat-row</value>
      <webElementGuid>6c10f94b-1a8a-48dc-ad9e-f83dd223e786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subir Adjunto'])[1]/following::mat-row[1]</value>
      <webElementGuid>e8f224d1-4351-4585-870f-38b2471610e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La presentación total no puede superar los 5 MB'])[1]/following::mat-row[1]</value>
      <webElementGuid>5b60c774-b1ea-43ba-8d1a-f3d548526513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-row</value>
      <webElementGuid>a1c8064b-8f42-4727-8c77-bd10b49c59dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-row[(text() = 'deletePrueba.pdf Público  Privado ' or . = 'deletePrueba.pdf Público  Privado ')]</value>
      <webElementGuid>11714fce-26f3-4a6b-b428-99a5f212f798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
