<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snack-bar-container_Eliminacin de adjunto p_541b0a</name>
   <tag></tag>
   <elementGuidId>0936493e-99d0-450d-bea9-d46bf4674ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-8']/snack-bar-container</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>snack-bar-container.mat-snack-bar-container.ng-tns-c39-18.ng-trigger.ng-trigger-state.mat-snack-bar-center.mat-snack-bar-top.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>snack-bar-container</value>
      <webElementGuid>4ed69601-a2d1-4841-b26a-02a9fb3e0c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-snack-bar-container ng-tns-c39-18 ng-trigger ng-trigger-state mat-snack-bar-center mat-snack-bar-top ng-star-inserted</value>
      <webElementGuid>d36b7f76-8edd-47d5-b59f-9a297fea71d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>d4ef081c-025a-43bd-9be1-df1b896c8d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminación de adjunto procesadaAceptar</value>
      <webElementGuid>b9af9f77-1d26-4ad9-baf2-0622f691417c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-8&quot;)/snack-bar-container[@class=&quot;mat-snack-bar-container ng-tns-c39-18 ng-trigger ng-trigger-state mat-snack-bar-center mat-snack-bar-top ng-star-inserted&quot;]</value>
      <webElementGuid>4b113047-18cd-466e-902d-31f514d0529a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-8']/snack-bar-container</value>
      <webElementGuid>9b94d006-c12f-485c-bf04-d5f30b1ef812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminación de adjunto procesada'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>12f36695-523a-496c-875b-057f1986a8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>0b1486a2-444a-4384-bbeb-58b44eef56ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//snack-bar-container</value>
      <webElementGuid>db848917-b47b-4757-bf73-669f464218c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//snack-bar-container[(text() = 'Eliminación de adjunto procesadaAceptar' or . = 'Eliminación de adjunto procesadaAceptar')]</value>
      <webElementGuid>ec2e7985-e417-4db2-95b1-5388e177e6c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
