<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snack-bar-container_Se ha firmado la Actuac_0f8f2c</name>
   <tag></tag>
   <elementGuidId>d06c12f6-ef67-4228-8e89-69fd4d10c7e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//simple-snack-bar/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>snack-bar-container.mat-snack-bar-container.ng-tns-c40-17.ng-trigger.ng-trigger-state.mat-snack-bar-center.mat-snack-bar-top.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>snack-bar-container</value>
      <webElementGuid>85688a55-f9ba-4c44-b123-8be3a91c7a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-snack-bar-container ng-tns-c40-17 ng-trigger ng-trigger-state mat-snack-bar-center mat-snack-bar-top ng-star-inserted</value>
      <webElementGuid>06621675-f8b4-48df-ae66-9efbd54973b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>53ec2712-1abd-4144-a6a7-9cc83b160085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Se ha firmado la Actuación 43566/2022 el día 12/12/2022 a las 16:56Aceptar</value>
      <webElementGuid>15613fa7-72d6-409a-8c42-44dcfffa474f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-7&quot;)/snack-bar-container[@class=&quot;mat-snack-bar-container ng-tns-c40-17 ng-trigger ng-trigger-state mat-snack-bar-center mat-snack-bar-top ng-star-inserted&quot;]</value>
      <webElementGuid>14b47636-f2c8-4db9-a5ab-acdf8a2ff61b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-7']/snack-bar-container</value>
      <webElementGuid>0e1a113e-f462-4b0f-833e-655ea2bceead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se ha firmado la Actuación 43566/2022 el día 12/12/2022 a las 16:56'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>dd8e4cd6-9743-4175-8aa8-6ca20e6f71b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>4bab44eb-7f98-43db-93ff-7d728b324a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//snack-bar-container</value>
      <webElementGuid>52fbecc9-4641-47d6-8a21-ee94c404af77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//snack-bar-container[(text() = 'Se ha firmado la Actuación 43566/2022 el día 12/12/2022 a las 16:56Aceptar' or . = 'Se ha firmado la Actuación 43566/2022 el día 12/12/2022 a las 16:56Aceptar')]</value>
      <webElementGuid>1d769487-8c3b-4de0-b772-7ab3cf1971fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
