<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snack-bar-container_Eliminacin de adjunto p_541b0a</name>
   <tag></tag>
   <elementGuidId>0936493e-99d0-450d-bea9-d46bf4674ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>snack-bar-container.mat-snack-bar-container.ng-tns-c39-18.ng-trigger.ng-trigger-state.mat-snack-bar-center.mat-snack-bar-top.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//simple-snack-bar/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>snack-bar-container</value>
      <webElementGuid>45aa32a2-92d3-4ed4-a049-5e0bfd36e663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-snack-bar-container ng-tns-c39-18 ng-trigger ng-trigger-state mat-snack-bar-center mat-snack-bar-top ng-star-inserted</value>
      <webElementGuid>e0d4be83-c553-488a-b3d0-61bbb465ee94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>143b2654-2f60-4b52-b563-4c7464a66f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminación de adjunto procesadaAceptar</value>
      <webElementGuid>7e9430df-cf91-4272-9065-70b057db4a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-8&quot;)/snack-bar-container[@class=&quot;mat-snack-bar-container ng-tns-c39-18 ng-trigger ng-trigger-state mat-snack-bar-center mat-snack-bar-top ng-star-inserted&quot;]</value>
      <webElementGuid>dce9d305-bae6-4d6e-83cf-d899f511e67e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-8']/snack-bar-container</value>
      <webElementGuid>d01a5f46-3502-40a9-a5a1-7c59d0393dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminación de adjunto procesada'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>5443eb78-4343-4ebc-9939-52cf05483f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Versión 22.1.0'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>707818f9-be7b-46ea-a5eb-fe4aaaff2610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//snack-bar-container</value>
      <webElementGuid>13f55065-6019-4bf8-9c7f-5f11940a47b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//snack-bar-container[(text() = 'Eliminación de adjunto procesadaAceptar' or . = 'Eliminación de adjunto procesadaAceptar')]</value>
      <webElementGuid>148c6cc8-b8a7-4094-ac08-ebc0279420a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
