<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_remove_red_eye</name>
   <tag></tag>
   <elementGuidId>d09ad21f-936e-4faf-9540-67a96c9a3b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='a-verVistaPrevia']/span)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.botones_margin > #a-verVistaPrevia > span.material-icons.tarjeta__col-izq--iconosDark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a172740b-fb94-4be8-8da0-0b50f55ba039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons tarjeta__col-izq--iconosDark</value>
      <webElementGuid>26bcaeb0-e404-47ec-98e0-2a5e76d0bd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>remove_red_eye</value>
      <webElementGuid>1aee7876-b75f-4b77-805a-3f2ba8171096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/modal-accion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body py-0&quot;]/app-adjunto[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid ng-star-inserted&quot;]/mat-table[@class=&quot;mat-table&quot;]/mat-row[@class=&quot;mat-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell-descargar mat-cell cdk-column-verAdjunto mat-column-verAdjunto ng-star-inserted&quot;]/span[@class=&quot;botones_margin&quot;]/button[@id=&quot;a-verVistaPrevia&quot;]/span[@class=&quot;material-icons tarjeta__col-izq--iconosDark&quot;]</value>
      <webElementGuid>6970083d-4d4d-43ac-8cb3-b55486bc5f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='a-verVistaPrevia']/span)[3]</value>
      <webElementGuid>281f48ec-f3bb-4774-9926-0d39673e9252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[1]/following::span[2]</value>
      <webElementGuid>d7114b40-7540-447a-afe9-7101e855bdff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICO'])[1]/following::span[3]</value>
      <webElementGuid>05e6febf-eb5d-4f93-afba-484a0abaeee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='get_app'])[1]/preceding::span[1]</value>
      <webElementGuid>7519884f-0180-48aa-aaa2-1bad315c6457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell[6]/span/button/span</value>
      <webElementGuid>052369d0-5f26-4ef5-a3b3-6358b84d31b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'remove_red_eye' or . = 'remove_red_eye')]</value>
      <webElementGuid>9f02ecf3-17d5-4503-bc8b-b813efdd84f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
