<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_435662022</name>
   <tag></tag>
   <elementGuidId>e345f008-727c-4210-b4dd-648c36f93ddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel[@class='mt-2 mat-expansion-panel ng-tns-c5-2 mat-expanded']//div[3]//span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c77dff86-3ca9-478e-a2f7-a62a6d0dd841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight--600</value>
      <webElementGuid>84189949-4321-4c11-99e5-30ea68da817d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>43566/2022</value>
      <webElementGuid>75c3e4ed-76a7-4268-be96-857038b61363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-0&quot;)/div[@class=&quot;mat-expansion-panel-body&quot;]/div[1]/div[1]/div[@class=&quot;mb-2&quot;]/span[@class=&quot;font-weight--600&quot;]</value>
      <webElementGuid>d6ff3f36-aff2-4ee0-a3be-5a4c1b62b763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-0']/div/div/div/div[3]/span[2]</value>
      <webElementGuid>3badae6a-4245-4e0b-a5fb-53a32e6654d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Actuación:'])[1]/following::span[1]</value>
      <webElementGuid>1638af05-8f9f-4b1b-85cc-4e62b00b2a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NES, RAM SOBRE OTROS PROCESOS SUMARISIMOS'])[1]/following::span[2]</value>
      <webElementGuid>1e3381fc-e5b7-4fe8-9fa9-3885ffa206d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='content_copy'])[2]/preceding::span[1]</value>
      <webElementGuid>1702fe0f-f888-49c9-80ac-4ba78b739dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tí­tulo:'])[1]/preceding::span[2]</value>
      <webElementGuid>9107ea6e-8835-4cc2-9a02-488ba53af190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='43566/2022']/parent::*</value>
      <webElementGuid>3a11d7c7-70b8-4c7d-996c-eab8f81effe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>ce2a6b08-8d7f-40c1-9df6-ef058bf00b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '43566/2022' or . = '43566/2022')]</value>
      <webElementGuid>00bc55e8-c16d-4d3f-aa34-161de6a8c15f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
