<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FIRMADA</name>
   <tag></tag>
   <elementGuidId>57d60a14-cb71-453a-a1e1-f83258bc483e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.etiqueta-estado--firmada.mr-2.etiqueta-detalle-valida.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='attach_file'])[1]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7300e9f2-d01d-4d8f-b4c2-89c3748392b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>etiqueta-estado--firmada mr-2 etiqueta-detalle-valida ng-star-inserted</value>
      <webElementGuid>54919e89-5537-43a1-90aa-fa42d76aa98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>36b28d04-8222-4a53-8abb-b23ba4ae9711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>popovertitle</name>
      <type>Main</type>
      <value>Información de la firma</value>
      <webElementGuid>a9153c6b-6b24-429d-a8a1-0484e1bb0cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>triggers</name>
      <type>Main</type>
      <value>mouseenter:mouseleave</value>
      <webElementGuid>10c163dd-6ecf-4cbd-b8af-d14c24194c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-popover-5</value>
      <webElementGuid>fa973d42-010a-4b78-9e79-ff0d04b529dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FIRMADA </value>
      <webElementGuid>fc57d94e-bde7-4c64-b36b-674bac8035eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-actuacion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;contenedor alto-pdf-viewer ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-auto mr-auto contenedor-pagina-etiquetas mt-2 mb-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;etiqueta-detalle-contenedor mb-3&quot;]/span[@class=&quot;etiqueta-estado--firmada mr-2 etiqueta-detalle-valida ng-star-inserted&quot;]</value>
      <webElementGuid>581406e8-89fc-447a-86c5-b2b6088a9a87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='attach_file'])[1]/following::span[2]</value>
      <webElementGuid>77685668-c5ec-4f9f-a103-5a8285e4470f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create'])[1]/following::span[2]</value>
      <webElementGuid>7e61dc57-b0b1-40e6-8d5b-fc82af4550c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Información de la firma'])[1]/preceding::span[1]</value>
      <webElementGuid>e964f67d-fb89-4c96-8286-d04d67c7d1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FIRMADA']/parent::*</value>
      <webElementGuid>4cafaae7-eb01-45e4-8a4d-ee4b97dcf7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/span</value>
      <webElementGuid>4b446baf-2853-4abb-b3be-724b695ab9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' FIRMADA ' or . = ' FIRMADA ')]</value>
      <webElementGuid>1e6b03be-2c03-49da-8255-ce36a833913e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
