<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_get_app</name>
   <tag></tag>
   <elementGuidId>2b9be7ef-1cfb-4f22-9f4d-0140c4b7fc1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='a-descargar']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.material-icons.icono-descarga</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7aecc655-9617-4ca7-823f-3defc505c0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons icono-descarga</value>
      <webElementGuid>b0876bf5-19f6-48e5-b436-106365968eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>get_app</value>
      <webElementGuid>9a5fc362-7273-4c2d-8cce-80e81a6076f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/modal-accion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body py-0&quot;]/app-adjunto[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid ng-star-inserted&quot;]/mat-table[@class=&quot;mat-table&quot;]/mat-row[@class=&quot;mat-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell-descargar mat-cell cdk-column-descargar mat-column-descargar ng-star-inserted&quot;]/a[@id=&quot;a-descargar&quot;]/span[@class=&quot;material-icons icono-descarga&quot;]</value>
      <webElementGuid>9fac9e06-6776-4749-a6c1-26bbb774e02e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a-descargar']/span</value>
      <webElementGuid>3a55287f-2fb7-4bf3-9ac6-153fbc8c58a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove_red_eye'])[3]/following::span[1]</value>
      <webElementGuid>027ec401-539e-40ff-a899-ac2e56f3b129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[1]/following::span[3]</value>
      <webElementGuid>0e2e3306-b0ec-4093-bcfd-efae34d6c8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='share'])[2]/preceding::span[1]</value>
      <webElementGuid>7922552f-0261-4373-9aa1-e35bd0d875b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='get_app']/parent::*</value>
      <webElementGuid>4e630614-eacb-41c5-b31b-8e074791246f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell[7]/a/span</value>
      <webElementGuid>66596281-047c-4f53-a918-6fb417503316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'get_app' or . = 'get_app')]</value>
      <webElementGuid>cf4676e4-7a82-4236-9e43-1f50b19eea60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
