<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BORRADOR</name>
   <tag></tag>
   <elementGuidId>c7e3d1b7-c67c-4379-b8cc-d50f111cc7f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[. = ' BORRADOR ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.etiqueta-detalle.etiqueta-estado--firmada.mr-2.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b9fb7a5-72c8-4c5d-8bde-fa65c1efda7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>etiqueta-detalle etiqueta-estado--firmada mr-2 ng-star-inserted</value>
      <webElementGuid>3f67c568-f540-4213-a338-1990fe388053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>978ea07d-0f2c-4328-be9e-eb97663789e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>popovertitle</name>
      <type>Main</type>
      <value>Información</value>
      <webElementGuid>d297e961-8746-4439-92d5-90487409f122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>triggers</name>
      <type>Main</type>
      <value>mouseenter:mouseleave</value>
      <webElementGuid>1dddf97a-5ceb-4654-8075-3486ff0b2fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-popover-0</value>
      <webElementGuid>50af0394-79be-4eb9-bff4-2f53a013c715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BORRADOR </value>
      <webElementGuid>7b5825c6-77bc-4bd8-ad77-a363f52839ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-actuacion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;contenedor alto-pdf-viewer ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-auto mr-auto contenedor-pagina-etiquetas mt-2 mb-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;etiqueta-detalle-contenedor mb-3&quot;]/span[@class=&quot;etiqueta-detalle etiqueta-estado--firmada mr-2 ng-star-inserted&quot;]</value>
      <webElementGuid>5e8cd6ba-463c-4ca4-a3a8-443a26bd6980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create'])[1]/following::span[1]</value>
      <webElementGuid>b0493c37-d1b5-4c69-9c42-c3ff2c0540ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Información'])[1]/preceding::span[1]</value>
      <webElementGuid>dca45e16-3970-44bf-a2aa-25a8c92e082f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BORRADOR']/parent::*</value>
      <webElementGuid>9768ced4-4c0c-44e9-aaf4-ffde72d1e3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/span</value>
      <webElementGuid>4f57144e-87b0-462b-b990-262c90358674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' BORRADOR ' or . = ' BORRADOR ')]</value>
      <webElementGuid>7a671751-469a-45e0-8c58-4ca99f6b96b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
