<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FIRMADA</name>
   <tag></tag>
   <elementGuidId>57d60a14-cb71-453a-a1e1-f83258bc483e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='attach_file'])[1]/following::span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.etiqueta-estado--firmada.mr-2.etiqueta-detalle-valida.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8fb1acd2-bd82-421b-af18-6bd9c098eb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>etiqueta-estado--firmada mr-2 etiqueta-detalle-valida ng-star-inserted</value>
      <webElementGuid>b97da556-d2ed-4d22-bc1c-3a23ea30985c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>b596724c-761b-41b6-b50b-f2e45ffc7b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>popovertitle</name>
      <type>Main</type>
      <value>Información de la firma</value>
      <webElementGuid>2b6a6a15-1fea-4608-a004-3f9735cb2b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>triggers</name>
      <type>Main</type>
      <value>mouseenter:mouseleave</value>
      <webElementGuid>141c0ff7-4370-4b61-8599-e97087ec419d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-popover-5</value>
      <webElementGuid>c98353a7-5a0d-4f2f-8d5c-b53a934bd708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FIRMADA </value>
      <webElementGuid>e20fb35a-ffe6-445f-8bcc-d967d4c42a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-actuacion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;contenedor alto-pdf-viewer ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-auto mr-auto contenedor-pagina-etiquetas mt-2 mb-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;etiqueta-detalle-contenedor mb-3&quot;]/span[@class=&quot;etiqueta-estado--firmada mr-2 etiqueta-detalle-valida ng-star-inserted&quot;]</value>
      <webElementGuid>de10d934-2749-4540-bbd2-0417bfd76656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='attach_file'])[1]/following::span[2]</value>
      <webElementGuid>341f6254-9dc9-4e14-b8f9-4b2e4384e761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create'])[1]/following::span[2]</value>
      <webElementGuid>28f9a7e6-db43-4092-911b-d9fafe79942b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Información de la firma'])[1]/preceding::span[1]</value>
      <webElementGuid>d8d7fabf-80a9-4507-aef4-45ef0c61b787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FIRMADA']/parent::*</value>
      <webElementGuid>a79f4a92-5d2d-490b-99b2-84ba34cf8b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/span</value>
      <webElementGuid>312f3a2e-8a41-40ca-adc3-3bec23e613fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' FIRMADA ' or . = ' FIRMADA ')]</value>
      <webElementGuid>62378119-d304-43d3-9e42-c791b74b9484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
