<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_clear</name>
   <tag></tag>
   <elementGuidId>457251a5-7fae-4208-927b-04ad3df2cb38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div[2]/app-adjunto/div/mat-table/mat-row/mat-cell[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.material-icons.icono-firma.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04556f11-9eba-4143-b305-43e9b75be4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons icono-firma ng-star-inserted</value>
      <webElementGuid>b70a080d-c050-4bc8-8a9f-be1f2e83fa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>clear</value>
      <webElementGuid>117f1f49-ccf7-4b56-a1c2-20e85fce128a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/modal-accion[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-body py-0&quot;]/app-adjunto[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid ng-star-inserted&quot;]/mat-table[@class=&quot;mat-table&quot;]/mat-row[@class=&quot;mat-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-column-firmado mat-column-firmado ng-star-inserted&quot;]/span[@class=&quot;material-icons icono-firma ng-star-inserted&quot;]</value>
      <webElementGuid>0490054f-3c6f-444d-804d-6d53873a4abc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/modal-accion/div[2]/app-adjunto/div/mat-table/mat-row/mat-cell[5]/span</value>
      <webElementGuid>9aca9351-592a-4afc-b1b5-0b3d7c97827e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICO'])[1]/following::span[1]</value>
      <webElementGuid>b3218e7f-031d-4a86-bf56-91da3a2d5bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IURIXQA, CAYT'])[1]/following::span[3]</value>
      <webElementGuid>e5681ccc-83f7-45b7-adb7-cb339e9b23a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove_red_eye'])[3]/preceding::span[1]</value>
      <webElementGuid>e2466e5e-cb01-4001-a231-8fdecce833a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='get_app'])[1]/preceding::span[3]</value>
      <webElementGuid>a811ccef-e715-4e08-af16-3dfa40d6440f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='clear']/parent::*</value>
      <webElementGuid>31830799-76b0-4eeb-9d61-34af4b0f0ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell[5]/span</value>
      <webElementGuid>63ea582f-2d6e-4834-8bdf-0ad5f08a146c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'clear' or . = 'clear')]</value>
      <webElementGuid>e8e91a82-0a00-4884-9f6f-e11cd12e909f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
