<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_more_vert</name>
   <tag></tag>
   <elementGuidId>f2192a81-ba8d-46d7-9f53-4661ec27cb7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='al-btnGroupDrop1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.material-icons.secContenedor__botones--menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3626dffe-4287-43a8-8972-cdc41968ed41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons secContenedor__botones--menu</value>
      <webElementGuid>c03c74bf-814b-475d-976f-f94c389941b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>dabd6bf5-c845-46e6-9278-a52d78d342f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-btnGroupDrop1&quot;)/span[@class=&quot;material-icons secContenedor__botones--menu&quot;]</value>
      <webElementGuid>742fe1c0-2af5-471d-89c5-c988b91ad40c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='al-btnGroupDrop1']/span</value>
      <webElementGuid>a47fd060-1334-446a-a0ae-1990216e8e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R35 - RESOLUCION - HABILITACION DE LA INSTANCIA'])[1]/following::span[2]</value>
      <webElementGuid>6c5d7a1c-f325-4b25-beff-e6cbf8b97dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='article'])[1]/following::span[3]</value>
      <webElementGuid>02528799-4802-45ba-ad42-568ffb4eaf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver Auditoría'])[1]/preceding::span[1]</value>
      <webElementGuid>f6c952c0-ee4a-49cd-9ed3-6a0c423f54cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Actuación'])[1]/preceding::span[1]</value>
      <webElementGuid>d7b7764f-25e9-4481-bb29-7bf3f01d763e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_vert']/parent::*</value>
      <webElementGuid>4a51076b-f469-4982-b683-c60362a2f458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/button/span</value>
      <webElementGuid>a4fb36e7-3bac-4782-bc9e-62e25f223b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>ae79d9dd-5ad4-4620-a2a8-800152f56c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
