<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_more_vert</name>
   <tag></tag>
   <elementGuidId>f2192a81-ba8d-46d7-9f53-4661ec27cb7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.material-icons.secContenedor__botones--menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='al-btnGroupDrop1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e4905f4-46ef-4389-b0a1-85eb3950a0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons secContenedor__botones--menu</value>
      <webElementGuid>4f9fac8d-83a6-49ed-8e34-6f1b1c7030e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>86712739-8d28-4e15-a2d0-dbeaa51e758e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-btnGroupDrop1&quot;)/span[@class=&quot;material-icons secContenedor__botones--menu&quot;]</value>
      <webElementGuid>c493ac00-f565-497e-8b97-fd05dcb4371b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='al-btnGroupDrop1']/span</value>
      <webElementGuid>6e5f7d62-e1c7-44ed-8960-ef2998837e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R35 - RESOLUCION - HABILITACION DE LA INSTANCIA'])[1]/following::span[2]</value>
      <webElementGuid>5100deec-7ed7-41a2-bdcc-e4664ceffdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='article'])[1]/following::span[3]</value>
      <webElementGuid>7223218c-2c27-4fdf-b716-c2e68969d91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver Auditoría'])[1]/preceding::span[1]</value>
      <webElementGuid>aa1e108a-83e2-424b-b24e-43455c267026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Actuación'])[1]/preceding::span[1]</value>
      <webElementGuid>5fc05de3-f4c7-434f-a93a-fce5945fbe85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_vert']/parent::*</value>
      <webElementGuid>3cd95642-3a0a-49b3-8905-0e10fd1a017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/button/span</value>
      <webElementGuid>ed7b8436-c1be-4299-855f-4c32da12c57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>e339c433-1809-41af-a019-e7cbf0ac94c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
