<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Privado_observaciones</name>
   <tag></tag>
   <elementGuidId>ea146f8e-9076-4385-9eca-a9eec4ae2386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-actuacion/div[2]/div[2]/div[1]/div/div/mat-horizontal-stepper/div[2]/div[1]/app-datos-iniciales/form/div/div[5]/mat-form-field/div/div[1]/div[3]/textarea</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#di-observaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f6558b29-e5e2-4445-a75d-61c516cc74fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Observaciones</value>
      <webElementGuid>1d1b161a-a9fe-492c-8a32-38da1651c89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored</value>
      <webElementGuid>7e42871b-6476-4d1e-b4d3-4bdbe3701c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>di-observaciones</value>
      <webElementGuid>17dde1cc-7273-43f4-957f-b7780beb5c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>5545f543-5d1c-4fc7-a7f6-4819a001e1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>observaciones</value>
      <webElementGuid>c629518c-e518-4491-9334-a06909428a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Observaciones</value>
      <webElementGuid>f1f332a5-8baf-4d4f-962f-c0ff24ac17da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3178d951-6e72-4e62-be1f-f1790fdd5685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>284c7657-67b3-4e65-8b0a-1480e3db7968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;di-observaciones&quot;)</value>
      <webElementGuid>de0bd518-0839-4aab-a1f2-a85ecfcec534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='di-observaciones']</value>
      <webElementGuid>64ca0831-513f-41fb-a1a9-b1c7e343b0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mab-datosInicialesForm']/div/div[5]/mat-form-field/div/div/div[3]/textarea</value>
      <webElementGuid>4583f5fc-7fec-4cd1-a946-e147c6832bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5da07723-664d-42be-a7f1-a42d951e87b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'di-observaciones' and @name = 'observaciones' and @placeholder = 'Observaciones']</value>
      <webElementGuid>02c7d88a-0c8c-4472-ab50-35302b20f5a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
