<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Con token  Sin token</name>
   <tag></tag>
   <elementGuidId>9ae67fa2-d2a5-4b6c-9458-5e361c804a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#al-dropdown-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='al-dropdown-menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>299377ad-f97c-48d9-9776-b0da651eb2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu dropdown-menu-right button-menu-estilo show</value>
      <webElementGuid>dfc2c56f-e7d2-42a2-be6e-67b6cdb66847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-dropdown-menu</value>
      <webElementGuid>23348852-1d4e-4787-846a-f2a663b402b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>a3d1282a-b5f7-44e2-b9ab-86275b35f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-placement</name>
      <type>Main</type>
      <value>bottom-end</value>
      <webElementGuid>727adb75-aad0-4ba4-bcb0-13650d90af04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Con token  Sin token </value>
      <webElementGuid>d2443567-b4f4-4316-ad2b-e326c835bfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-dropdown-menu&quot;)</value>
      <webElementGuid>27faae00-1173-41cf-bf8a-b470b35cbc76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='al-dropdown-menu']</value>
      <webElementGuid>db37ea5c-ef66-447d-8656-93a742e3d844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar'])[1]/following::ul[1]</value>
      <webElementGuid>b7d4f985-4684-4afc-9f24-a6a36544d7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilidad'])[1]/following::ul[1]</value>
      <webElementGuid>4b18a933-6ba5-4e84-bc0d-70401dd327f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>c0b980f7-f84b-4756-aa16-a43e6457be82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'al-dropdown-menu' and (text() = ' Con token  Sin token ' or . = ' Con token  Sin token ')]</value>
      <webElementGuid>650a2f1a-d538-465c-b369-ebef6ea86a1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
