<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Con token  Sin token</name>
   <tag></tag>
   <elementGuidId>9ae67fa2-d2a5-4b6c-9458-5e361c804a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='al-dropdown-menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#al-dropdown-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>fa1f0b7c-fa78-4d38-b519-c8782772d05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu dropdown-menu-right button-menu-estilo show</value>
      <webElementGuid>19d26457-c35f-47f6-8d18-d7bf0b8a4062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-dropdown-menu</value>
      <webElementGuid>07bff16c-1fac-4836-a443-7c9b98782197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>6f6a64a6-8378-4a74-ba52-5dc21f231ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-placement</name>
      <type>Main</type>
      <value>bottom-end</value>
      <webElementGuid>fb0cd742-ec40-48da-a704-67affdde7ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Con token  Sin token </value>
      <webElementGuid>1682defe-5159-4324-a06d-5208dad83e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-dropdown-menu&quot;)</value>
      <webElementGuid>1e7a2c23-945e-41b6-8664-07533828ad49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='al-dropdown-menu']</value>
      <webElementGuid>7faef65d-83b5-4a27-9d26-91dd1b80e862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar'])[1]/following::ul[1]</value>
      <webElementGuid>bce8edd8-5ef0-4276-8474-e6b739b3b1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilidad'])[1]/following::ul[1]</value>
      <webElementGuid>60fe75ab-af36-48aa-99c1-9f8d0c3c04cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>cb88d91f-f9a5-4ebe-84f9-2a39434748ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'al-dropdown-menu' and (text() = ' Con token  Sin token ' or . = ' Con token  Sin token ')]</value>
      <webElementGuid>2f92e5d0-431e-4334-b39c-cf0d32406e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
