<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Con token  Sin token</name>
   <tag></tag>
   <elementGuidId>9ae67fa2-d2a5-4b6c-9458-5e361c804a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='al-dropdown-menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#al-dropdown-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>9ba0f3c5-1c2a-4971-8f9f-783cc5b79c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu dropdown-menu-right button-menu-estilo show</value>
      <webElementGuid>79165a21-0ee4-4e83-9a93-f129f43518b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>al-dropdown-menu</value>
      <webElementGuid>ddce1132-9aba-460a-afb3-adbe2902eee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>c1bfddc1-c2fe-4773-9f0c-e54239090fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-placement</name>
      <type>Main</type>
      <value>bottom-end</value>
      <webElementGuid>36aef95d-7e5e-475c-9166-57320a62d92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Con token  Sin token </value>
      <webElementGuid>0a1236cf-fa31-469c-a95a-08cad3d1b665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;al-dropdown-menu&quot;)</value>
      <webElementGuid>9542f0fd-0f7f-4e8f-b25b-6c45259071a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='al-dropdown-menu']</value>
      <webElementGuid>6d5a65fb-6480-41ce-b56d-4b98f90e0762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar'])[1]/following::ul[1]</value>
      <webElementGuid>4f194fd0-cc74-4e00-8efd-6d266017b8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibilidad'])[1]/following::ul[1]</value>
      <webElementGuid>4839bab0-2761-41ff-a04a-e60d2302a3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>d313bf60-7ab2-44ef-9e9b-d6d3cd01fa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'al-dropdown-menu' and (text() = ' Con token  Sin token ' or . = ' Con token  Sin token ')]</value>
      <webElementGuid>0114dd11-89b8-478f-9259-f7a0a765be2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
