<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_filter_alt_codigo</name>
   <tag></tag>
   <elementGuidId>65e1c605-46f7-45af-b12e-45d64994a183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mab-ingresarCodigo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-form-field[@id='prueba']/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mab-ingresarCodigo' and @name = 'codigo' and @placeholder = 'Código' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be9a5b27-ce14-4f69-8692-883e43b359f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>db98dd2b-937c-4721-b256-c7128e0c3169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>codigo</value>
      <webElementGuid>4f43d1aa-87de-4df0-8ec8-e21e94120eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mab-ingresarCodigo</value>
      <webElementGuid>34d5105d-4fb4-42d2-b337-d6e6556fe87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codigo</value>
      <webElementGuid>9c7424cb-f67c-4449-987a-5d658f86f6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase()</value>
      <webElementGuid>3f75fb49-6fe8-45cb-9de1-298dfaef78f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>f8dad34f-dbb4-4011-9631-1bda04e8ca52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ef40cdb-fd11-45c7-8dc1-20a6a7f3ca9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1cfe6dbc-7b72-47af-9c0b-754397e8b239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>79f9a52b-c961-467a-8f18-de89872e7ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mab-ingresarCodigo&quot;)</value>
      <webElementGuid>bfa55c32-afd7-4a10-9941-61601043a797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mab-ingresarCodigo']</value>
      <webElementGuid>4326695d-e38a-42b6-8b37-b4c39f3252bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-form-field[@id='prueba']/div/div/div[3]/input</value>
      <webElementGuid>321a0da3-2fee-4a61-925c-facd9026e8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>e3be5415-b8d3-4670-90b2-977449c06ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mab-ingresarCodigo' and @name = 'codigo' and @placeholder = 'Código' and @type = 'text']</value>
      <webElementGuid>76e763f3-e767-4edf-a71d-2c40112be19f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
