<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Privado_observaciones</name>
   <tag></tag>
   <elementGuidId>8408f879-7528-4962-81d3-5df412b21371</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#di-observaciones</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'di-observaciones' and @name = 'observaciones' and @placeholder = 'Observaciones']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-actuacion/div[2]/div[2]/div[1]/div/div/mat-horizontal-stepper/div[2]/div[1]/app-datos-iniciales/form/div/div[5]/mat-form-field/div/div[1]/div[3]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9fe37d39-2d53-476e-a4f8-c4c2be5265aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Observaciones</value>
      <webElementGuid>2d98acfb-fff4-44f7-9be0-d0c10539f15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored</value>
      <webElementGuid>cbf64840-58f1-4f28-9c00-116e6d3886c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>di-observaciones</value>
      <webElementGuid>8066e3ce-df3c-4b8f-af7a-1a7cc567d94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>58d056e0-ee94-47fa-a78c-370550f04bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>observaciones</value>
      <webElementGuid>4f21b098-0055-4d8e-93a9-4380d49bd17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Observaciones</value>
      <webElementGuid>17a4ff2b-10d8-44f6-a48a-b76f9876ce98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1eed11df-26e7-44a2-ba01-3e53e80f4bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad67045e-e8b5-4d98-bc19-600c3e028075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;di-observaciones&quot;)</value>
      <webElementGuid>a9b05287-e6e2-454d-8a18-d2e2d8c0ddfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='di-observaciones']</value>
      <webElementGuid>343dcf75-8cdd-4d4d-b272-7f6aec86cba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mab-datosInicialesForm']/div/div[5]/mat-form-field/div/div/div[3]/textarea</value>
      <webElementGuid>8b13c895-88f1-45a5-ad72-26f92cbd1228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>57c6f336-1b39-4640-aefa-3b273bca4470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'di-observaciones' and @name = 'observaciones' and @placeholder = 'Observaciones']</value>
      <webElementGuid>cd203a74-7808-4c15-acd5-ce79dc3fce16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
